aaa=[ 'Facebook users', 'Tesla drivers', 'Women, Minority Groups', 'General public', 'unknown', 'Microsoft', 'Motorists',
     'Black people', 'Women', 'Minority Groups', 'internet users', 'Uber drivers', 'ChatGPT users', 'minors',
     'Children', 'patients', 'Twitter Users', 'Accused People', 'Amazon Customers', 'email users', 'pedestrians',
     'Amazon users', 'Facebook users having posts about painful events, Facebook users', 'Jewish people', 'Bing users',
     'San Francisco firefighters, San Francisco Fire Department', 'TikTok users', 'public figures, celebrities',
     'Google users', 'Navya, Keolis North America, bus passengers', 'Elaine Herzberg, pedestrians',
     'Starbucks employees', 'Robotics Consultant', 'Airplane Passengers, Airplane Crew', 'pedestrians, Motorists',
     'Gmail Users', 'Wikimedia Foundation, Wikipedia Editors, Wikipedia Users', 'People with Twins', 'Asian People',
     'Apple, Device Owners', 'Oliver Haberstroh, Neighbors', 'Fire Victims', 'Dong Mingzhu', 'Medical Residents',
     'Yandex Users', 'Individual Kaggle Competitors', 'drivers in Jokkmokk, drivers in Sweden, Volvo', 'Carollers',
     'Child', 'Ramji Lal', 'People with Dark Skin', 'Store Patrons', 'Oakland Residents', 'Knightscope', 'Joshua Brown',
     'Alex Harker', 'my_handy_design', 'Australian welfare recipients', 'OpenAI', 'DAO Token Holders',
     'Mountain View municipal bus passengers, Mountain View municipal bus',
     'Chinese Communist Party, Tencent Holdings, Microsoft, Turing Robot',
     'unnamed Palestinian Facebook user, Palestinian Facebook users, Arabic-speaking Facebook users, Facebook users',
     'Facebook users, Facebook users interested in COVID information, Facebook users interested in the US Presidential Election',
     'International Baccalaureate students', 'Jewish people, Google Images users',
     'non-white neighborhoods, communities of color', 'Jewish people, Jewish public figures',
     'patients of minority groups, low-income patients, female patients, Hispanic patients, patients with Medicaid insurance',
     'Leaving Certificate exam takers, Irish Department of Education and Skills',
     'Robert Julian-Borchak Williams, Black people in Detroit', 'job applicants using HireVue, HireVue customers',
     'New York City low-income communities', 'Stanford Medical frontline workers, Stanford Medical residents',
     'Buenos Aires children', 'YouTube users',
     'Facebook users, Facebook users interested in the Lekki Massacre incident',
     'Facebook users of minority groups, non-American-born Facebook users, non-Christian Facebook users, Facebook users interested in accessibility, Facebook users interested in Hispanic culture',
     'Cogo Guebara, unnamed woman injured in the fight', 'Houston Independent School District teachers',
     'livestream viewers', 'Black patients, African-American patients', 'dark-skinned people, dark-skinned women',
     'Apple Card female users, Apple Card female credit applicants',
     'Deliveroo workers with legitimate reasons for cancelling shifts, Deliveroo workers',
     'Amazon Flex employees, Amazon Flex drivers',
     'California low-income neighborhoods, California communities of color',
     'Korean Facebook Messenger users, Korean people of gender minorities, Korean people with disabilities',
     'Genderify customers, gender minority groups', 'Jovani Maldonado, Benjamin Maldonado, California public',
     'Dutch Tax Authority, Dutch families', 'Twitter Users, Twitter non-white users, Twitter non-male users',
     'Troy residents, Troy Police Department, Syracuse residents, Syracuse Police Department, San Francisco residents, San Francisco Police Department, San Antonio residents, San Antonio Police Department, New York City residents, New York City Police Department, Fall River residents, Fall River Police Department, Chicago Residents, Chicago Police Department',
     'Lucie Inland', 'Amazon delivery drivers, Amazon workers', 'Reddit users',
     'Arkansas Medicaid waiver program beneficiaries, Arkansas healthcare workers',
     'Lamya Robinson, Black Livonia residents', 'Rekognition users, arrested people', 'Uyghur people',
     'Xsolla employees', 'Black college students, Latinx college students, indigenous students', 'Libyan soldiers',
     'Black people, Facebook users', 'Muslims', 'University of Toronto BIPOC students',
     'Moshe Har Shemesh, Israeli people having tax fines',
     "internet users with disabilities, web accessibility vendors' customers",
     'Facebook users, Facebook content creators', 'California bar exam takers, flagged California bar exam takers',
     'Gilberto Alcazar Lopez, Maria Guadalupe Nieves-Lopez', 'Amazon fulfillment center workers',
     'University of Illinois students of color, University of Illinois students',
     'TikTok users, TikTok users under 18 years old', 'TikTok users, TikTok content creators',
     'Antonio Radic, YouTube chess content creators, YouTube users',
     "Kristin Livdahl's daughter, Amazon Echo customers, children using Alexa", 'SoftBank',
     'female Facebook users, Black Facebook users, male Facebook users',
     'Facebook users, LinkedIn users, YouTube users, Twitter Users, Netflix users',
     'TikTok content creators of marginalized groups', 'Sennett Devermont, Beverly Hills citizens',
     'Fuzhou Zhongfang Marlboro Mall goers', 'news sites',
     'University of Texas at Austin PhD applicants of marginalized groups',
     'Google Maps users traveling in Sierra Nevada, Google Maps users traveling in the mountains',
     'Paula Knight, Bath officials, UK public', 'San Francisco city government', 'sepsis patients',
     'people attempting suicides', 'Facebook users of small language groups, Twitter users of small language groups',
     'Amazon workers, Amazon delivery drivers', 'Target customers',
     'Facebook users of disabilities, adaptive fashion retailers', 'Hong Kong bank manager', 'inmates of color',
     'people having non-Caucasian facial features', 'Zillow Offers staff, Zillow', 'Black patients',
     'LGBTQ people, LGBTQ people of color, non-American LGBTQ people', 'Jade Thirlwall, Leigh-Anne Pinnock',
     'Facebook users of minority groups, Facebook users', 'UK ETS past test takers, UK ETS test takers, UK Home Office',
     'Natural Cycles users, Women',
     'Rohingya people, Rohingya Facebook users, Myanmar public, Facebook users in Myanmar, Burmese-speaking Facebook users',
     'Ocado', 'Eric Horvitz, Tesla drivers', 'Amaya Ross, Black students, Black test-takers',
     'Oregon State University, freight train crew', 'São Paulo Metro users, São Paulo citizens',
     'Pasco residents, Pasco Black students, Pasco students with disabilities', 'LinkedIn users',
     'Malaysian convicted people', 'unnamed Australian telecommunications company', 'Tinder users over 30 years old',
     'Korean public', 'Black WeChat users', 'Cruise vehicle', 'trans women, women of color',
     'Cruise vehicles, Cruise driver employee', 'Doctors, COVID patients',
     'Volodymyr Zelenskyy, Ukrainian social media users, Ukrainian public', 'San Francisco public, Cruise customers',
     'Tesla owner, Vision Jet owner', 'sex workers, Airbnb users', 'small businesses on Facebook',
     "unnamed UK-based energy firm's CEO", 'Spanish victims of gender violence', 'road engineer',
     'underrepresented groups, Minority Groups',
     'American physicians, American pharmacists, American patients of minority groups, American patients',
     'Google Docs users', 'Shophie Wilmès, Belgian government', 'Zhihu employees, Chinese tech workers',
     'Black students', 'fair visitors', 'Target, Target customers', 'TikTok users, TikTok new users',
     'delivery truck, pedestrians, Tesla drivers', 'Ever AI users',
     'Instagram users, Snapchat users, American social media users',
     'Salta teenage girls, Salta girls of minority groups', 'Naver customers', 'rhinos in conservation',
     'people with disabilities', 'Facebook content moderators', "pseudonymous Estée Lauder's former staff",
     'XPeng Motors customers', 'Pakistani citizens', 'Honolulu homeless people', 'John Bernal, San Jose public',
     'Ukrainian social media users', 'Ping An customers, Chinese minority groups', 'Thoughts users, Twitter Users',
     'Hive Box customers', 'WeChat Pay users', 'students, low-income minority students, Teachers',
     'oncologists, cancer patients', 'Yoshihiro Umeda, pedestrians, Tesla drivers', 'Umesh Ramesh Dhake',
     'Jeremy Beren Banner, Tesla users', 'Mark Molner', 'Gao Yaning, Tesla drivers', 'Brian Hofer',
     'Intellectual Property rights holders', 'Indian voters, Indian social media users, Indian women journalists',
     'tourists, Waze users', 'YouTube users, YouTube content creators', 'the Gilliam family',
     'Tumblr content creators, Tumblr users', 'tourists, Apple Maps users', 'Denise Green', 'Los Gatos residents',
     'children of minority groups, families of minority groups',
     'Sherman Oaks residents, Waze users, Los Angeles city government', 'child named Christopher',
     'Twitter, Twitter Users, Twitter users participating in COVID-19 discussions',
     'Landon Embry, motorcyclists, Tesla drivers', 'small businesses on Amazon, Amazon Customers',
     'FaceApp non-binary presenting users, FaceApp transgender users, FaceApp users', 'internet social platform users',
     'Chicago drivers', 'unnamed property owner', 'The Good Guys customers, Kmart customers, Bunnings customers',
     'UK drivers', 'non-TPI-registered Grab drivers, Grab drivers in Indonesia, Grab drivers',
     'US naturalized citizens, US immigrants, US citizenship applicants, US immigration applicants',
     'San Francisco homeless people',
     'Renren, Buding Movie Tickets, Yi Xia, Dangdang, Chinese startups, Chinese companies',
     'victims of crimes documented on social media, investigative journalists, International Criminal Court investigators, International Court of Justice investigators, criminal investigators',
     'Michael Williams', 'Replika users, Replika male users, Replika',
     'San Francisco traffic participants, San Francisco public', 'Uyghur people, Turkic Muslim ethnic groups',
     'Google Photos users residing in Illinois, Google Photos users, Illinois residents',
     'Virginia convicted felons, Virginia Black offenders, Virginia young offenders',
     'social media users, Instagram users, Facebook users',
     'neighborhoods of color, Brown communities, Black communities, Adam Toledo', 'US schools, US students',
     'Minority Groups, underrepresented groups', 'YouTube young male users, YouTube male users, Caleb Cain',
     'Pa Edrissa Manjang, Uber Eats Black delivery drivers', 'Jewish people, BlenderBot 3 users',
     'Facebook users sharing photo evidence of slavery, Facebook users', 'Google Lens users',
     'Cruise passengers, Toyota Prius passengers', "Olivia Solon, Olivia Solon's Facebook connections",
     'You You Xue, Tesla drivers', 'Nabla customers', 'Ousmane Bah, NYC Black people, NYC Black young people',
     'Tesla drivers, Culver City Fire Department', 'UK visa applicants from some countries',
     'Silicon Valley traffic participants, Silicon Valley residents',
     'TikTok male teenager users, TikTok male users, TikTok teenage users, TikTok users, TikTok',
     "Derrick Monet, Jenna Monet, the Monets' family", 'Black women, Black people, Google users',
     'Japanese pornographic actors', 'Laguna Beach Police Department', 'Facebook users, Twitter Users, YouTube users',
     'Waymo passengers', 'police investigators',
     'California Department of Motor Vehicles, Tesla customers, California residents',
     'Coffee Meets Bagel users having no ethnicity preference, Coffee Meets Bagel users',
     'local law enforcement officers', 'YouTube users, YouTube climate-skeptic users',
     'unnamed Tesla driver, Tesla drivers', 'Henn na Hotel guests, Henn na Hotal staff', 'The Vindicator',
     'job candidates using MyInterview, job candidates using Curious Thing, employers using MyInterview, employers using Curious Thing',
     'YouTube users skeptical of US election results', '15.ai, 15.ai users', 'Honda customers',
     'Nissan drivers, traffic participants', 'unnamed woman passenger',
     'The Seed Company by E.W. Gaze, businesses on Facebook', 'Bucheon citizens',
     'Sunnyside beachgoers, Marie Curtis beachgoers, Toronto citizens',
     'Twitter left-leaning politicians, Twitter left-leaning news organizations, Twitter left-leaning users, Twitter Users',
     'Marietje Schaake', 'unnamed 22-year-old male driver, Tesla drivers', 'Instagram users',
     'William Varner, unnamed passenger',
     "Lalani Erika Renee Walton, Arriani Jaileen Arroyo, Lalani Erika Renee Walton's family, Arriani Jaileen Arroyo's family, TikTok young users, TikTok users",
     'iPhone Face ID users, iPhone X Face ID users', 'Notting Hill Carnival goers',
     'students at Charlotte Mecklenburg Schools, teachers at Charlotte Mecklenburg Schools, security officers at Charlotte Mecklenburg Schools',
     'Women of Sex Tech conference attendants, Women of Sex Tech conference organizers',
     'Facebook users posting legitimate COVID-19 news, Facebook users', 'Instagram users, Facebook users',
     'a software engineer named Mark, parents using telemedicine services',
     'Teachers, non-cheating students, cheating students',
     'Marcus Rashford, Jadon Sancho, Bukayo Saka, Facebook users, Instagram users, Twitter Users',
     "Sirey Zhang, Geisel School of Medicine's students, Geisel School of Medicine's professors, Geisel School of Medicine's accused students",
     'FInals attendees, falsely accused Finals attendees', "Walter Huang's family, Walter Huang",
     'museums on Facebook, Facebook users interested in arts, Facebook users', 'TheFaceTag app users',
     'TikTok young users, TikTok users',
     'call center agents having non-Midwestern-American accent, people having non-Midwestern-American accent',
     'unnamed Tesla owner, Tesla drivers', 'Stability AI, deepfaked celebrities', 'Connecticut State Police', 'none',
     'Russian pornographic actresses, Russian sex workers', 'YouTube young users, YouTube users', 'Nijeer Parks',
     'Jisuk Mok, Frisco residents', 'vehicle repair shops, vehicle owners', 'unnamed Florida teenager',
     'UK immigrant newlyweds', 'Halle Bailey, Black actresses', 'historically disadvantaged groups',
     "Google's competitor shopping services", 'TuSimple, State of Arizona',
     'Facebook users posting about Plymouth Hoe, Facebook users in Plymouth Hoe, Plymouth Hoe residents',
     'women in need of abortion services, women having unexpected or crisis pregnancies',
     'unemployed Michigan residents falsely accused of fraud, unemployed Michigan residents', 'apartment renters',
     "Danielle's family, Amazon Echo users", 'Weibo, Chinese government', "Jeremy Banner, Jeremy Banner's family",
     'Black Google Home Mini users, Google Home Mini users', "Sebastian Galassi, Sebastian Galassi's family",
     'transgender Uber drivers', 'Stephan de Vries', 'Filipinos', 'the Karnataka government, Kannada speakers',
     'poor neighborhoods, neighborhoods of color',
     'students, Rock Hill School students, Pinecrest Academy Horizon students',
     'Transgender YouTubers, transgender people',
     'young men having credit scores, people scored on old scoring versions, people changing addresses frequently',
     'political organizations, political candidates', 'Twitter Users, Twitter',
     'Finland National Bureau of Investigation', 'Xi Jinping, Aung San Suu Kyi',
     'Real Women in Trucking, older female blue-collar workers', 'low digitally skilled Facebook users',
     'Uber drivers in India', 'digital artists, artists publishing on social media, artists',
     "victims of FTX's collapse, Twitter Users", 'women using Lensa AI, Asian women using Lensa AI',
     'Canadian students', 'XPeng driver', 'traffic participants, emergency vehicles, Cruise passengers, Cruise',
     'HSBC UK customers, Dan Simmons', 'Silvon Simmons', 'Kelly Conlon, Alexis Majano', 'Airline Passengers',
     'low-income communities, communities of color, Black Chicago residents', 'traffic participants, Tesla drivers',
     'Coupang suppliers, Coupang customers', 'traffic participants',
     'small businesses in India, Amazon customers in India', 'Michael Oliver, Black people in Detroit',
     'travelers in Korean airports', 'US Air Force, UK Royal Air Force, Kevin Main, David Williams',
     'mass shooting victims, Durham residents, Durham Police Department', 'Twitch users, Vedal',
     'research participants, Koko customers', 'Kenyan Sama AI employees', 'Getty Images, Getty Images contributors',
     'Replika users', 'plagiarized entities, CNET readers',
     'San Francisco residents, San Francisco firefighters, San Francisco Fire Department',
     'Apple Watch users doing winter activities, ski patrols, emergency dispatchers',
     'people having medical photos online', 'LinkedIn users, Instagram users, Facebook users', 'OpenAI, Microsoft',
     'racial minorities', "McDonald's customers", 'Walmart employees',
     'gender minority groups, racial minority groups, underrepresented groups in training data',
     'Palestinians residing in the West Bank', 'Souther Co-op customers', 'political opposition in Uganda',
     'Facebook users speaking Swahili, Facebook users speaking English, Facebook users',
     'Chinook Centre mall goers, Market Mall goers',
     'artists submitting in the digital arts category, digital artists, artists', 'Amazon delivery drivers',
     'SIT Acronis Autonomous', 'A-level pupils, GCSE pupils, pupils in state schools, underprivileged pupils',
     "OpenAI, people having personal data in GPT-2's training data", 'Black residents in Edmonton',
     'Black people in Brazil, Black people in Bahia',
     'interviewers of remote-work positions, employers of remote-work positions',
     'YouTube content creators, Twitch content creators, TikTok content creators, Instagram content creators',
     'WNY Gardeners, gardening Facebook groups, Facebook users in gardening groups',
     'Palestinian social media users, Facebook users, Instagram users, Twitter Users, Facebook employees having families affected by the conflict',
     'Google Pixel 6a users', 'Thai citizens, elder Thai citizens',
     'Molly Rose Russell, the Russell family, teenage girls, teenagers', 'Amazon warehouse workers',
     'young TikTok users, TikTok users, Gen Z TikTok users', 'Tesla drivers, horse-drawn carriages',
     'Minority Groups, Meta AI, Meta, Facebook, Minority Groups', 'Latitude',
     "Shannon Carpenter, McDonald's customers residing in Illinois, McDonald's customers",
     'Facebook users speaking East African languages, Facebook users in East Africa',
     "pseudonymized psychiatrist's patients, pseudonymized psychiatrist, patients, healthcare providers",
     'sex workers using Facebook', 'Stack Overflow users, Stack Overflow',
     'live-stream ceremony viewers, King Maha Vajiralongkorn', 'ChatGPT users, OpenAI', 'Black State Farm customers',
     'gay men in New York City, Julio Ramirez', 'foreign journalists in Henan, international students in Henan',
     'Black people in Louisiana, Randall Reid', "US Navy, Nathan White's family, Nathan White",
     'Spanish-speaking Instagram users', 'Immunefi', 'CNET readers', 'Frauke Zeller, David Harris', 'Black taxpayers',
     'Twitch users, transgender communities, LGBTQ communities', 'Teachers, students', 'Google, Google shareholders',
     'Tigrinya-speaking Facebook users, Facebook users in Ethiopia, Ethiopian public, Afaan Oromo-speaking Facebook users',
     'Replika users, Replika', 'victims in Paris attacks, Nohemi Gonzalez family, Nohemi Gonzalez',
     'Tesla drivers, city traffic participants, Tesla',
     'Maya Higa, female streamers, female content creators, @Sweet Anita, @QTCinderella, @Pokimane',
     'Vanderbilt University students, Vanderbilt University', 'Mohammed Khadeer',
     'Haitian asylum seekers, African asylum seekers, Black asylum seekers', 'Lloyds Bank',
     'Venezuelan people, social media users', 'Clarkesworld', "Ben Perkin's parents, Perkins family",
     'unnamed female college student', 'Twitter Users, social media users',
     'Black families in Allegheny, households with disabled people in Allegheny, Hackneys family',
     'Family and Friends of Deceased, Belgian Man', 'Pope Francis',
     'Italian children, Italian minors', 'Starship Technologies', 'political campaigns, Facebook users',
     'Centrelink account holders',
     'Your CBD Store, University of Pittsburgh Police Department, Phillipsburg High School, Hempstead High School, Dubuque Police Department, Bellefonte Area High School',
     'Justine Hsu', 'Universal Music Group, The Weeknd, Drake', 'Uber drivers, gig workers, Amazon delivery workers',
     'Amazon', 'racial minority groups, Women, gender minority groups',
     "Facebook's children users, Instagram's children users", 'Jennifer DeStefano, DeStefanos family',
     'Texas A&M University students', 'Twitter Users, Stock Holders, Family of People Near Pentagon',
     'Kemal Kilicdaroglu, Muharrem İnce',
     'Ronald L. Haeberle, Ron Haviv, Raymond D’Addario, Lynsey Addario, Lee Miller, Larry Towell, James Nachtwey',
     'Tillman Mitchell, the Mitchells family', 'Paul Tremblay, Mona Awad, authors of copyrighted works',
     'Alexa children users', 'research grant administrators, research grant applicants',
     'internet users, Children, social media users', 'Clive Kabatznik, Bank of America',
     'Hawaiian government, General public, American government',
     'Barack Obama, Oprah Winfrey, Jamie Foxx, Joan Rivers, Phil McGraw, Yahoo! News, E! News, TikTok, General public',
     "Queen Elizabeth II, British Royal Family, British Royal Family's staff, Jaswant Singh Chail, General public",
     'Facebook Messenger users',
     'Microsoft, Microsoft employees, Third parties relying on the confidentiality of the exposed data',
     'Slovakian electorate, Monika Todova, Michal Šimečka, Democratic process in Slovakia', 'Gizmodo journalists',
     'Non-cisgender individuals, LGBTQ+ community',
     'Black men who underwent lung function tests between 2010 and 2020 and potentially received inaccurate or delayed diagnoses and medical interventions due to the biased algorithm',
     'Children, General public, minors, teenagers',
     'Children whose data was collected and used for advertising, Schools and teachers who were misinformed and burdened with COPPA compliance responsibilities without adequate disclosure',
     'Consumers relying on accurate image categorization, members of racial and ethnic minorities who risk being stereotyped or misrepresented',
     'Chris Cowell', 'Porcha Woodruff', 'Rona Wang, Racial minorities who may have experienced the same result',
     'Potential users of the Savey Meal-bot', 'pedestrians, General public', 'Unnamed female students, Francesca Mani',
     'Unnamed employee of South Gyeongsang province produce distribution center',
     'Minors Exploited in the Images, General public',
     'Wolf Blitzer, Tom Hanks, Sanjay Gupta, Sally Bundock, Robin Williams, public figures, MrBeast, Matthew Amroliwala, Jesse Waters, Ian Hanomansing, General public, Gayle King, celebrities',
     'Keir Starmer, General public, British Labour Party',
     'Medicare Advantage Plan Patients, Healthcare Providers (Doctors and Therapists), elderly patients',
     'Romanians in the United Kingdom, Greeks in the United Kingdom, Bulgarians in the United Kingdom, British public, Albanians in the United Kingdom',
     'Anonymous female high school students', 'Federal Navy Credit Union Customers',
     'Rite Aid customers who were women, Rite Aid customers who were minorities, Rite Aid customers',
     'Sikh people, President Joe Biden, Pope Francis, Navajo people, Minorities, Hillary Clinton, General public, Donald Trump',
     'General Motors, Chevrolet of Watsonville', 'Amazon, Amazon sellers, Amazon Customers',
     "George Carlin's estate, Kelly Carlin, George Carlin",
     'Krista Perry, Larissa Martinez, Jay Baron, digital artists', 'Taylor Swift, General public', 'Georgie Purcell',
     'Steve Harvey, Sean “Diddy” Combs, General public, Denzel Washington, Black celebrities, Bishop T.D. Jakes',
     'General public, Chatbot users', 'Jake Moffatt', 'Unnamed owner of tow truck', 'Bobbi Althoff',
     'Julien Fanciulli, General public, France 24', 'Bicyclist', 'Unnamed middle school students',
     'President Joe Biden, transgender people', 'Joe Rogan, Joe Rogan fans, TikTok users',
     'YouTube users, Twitter Users, Synthesia, Facebook users', 'Voice Actors',
     'Derek Mobley, applicants with disabilities, applicants over 40, African American applicants',
     'Scarlett Johansson, female celebrities, Emma Watson', 'John Piscitella', 'Jonathan Faridian, DoNotPay customers',
     'OpenAI, TaskRabbit worker', 'social media users, 2023 Turkey–Syria earthquake victims',
     'Frances Walter, elderly patients', 'Marvin von Hagen, Seth Lazar, Microsoft, OpenAI, Bing Chat users',
     'Vietnamese Facebook users', 'Lucy Goetz, high school students', 'Randal Quran Reid', 'Amazon Fresh',
     'Roomba J7 device owners in project IO, iRobot, Scale AI', 'Women, underage girls, female celebrities',
     'transgender travelers, gender-nonconforming travelers',
     'anonymous Pashto-speaking refugee, Pashto-speaking asylum seekers, Dari-speaking asylum seekers',
     'COVID-19 patients, COVID-19 healthcare providers', 'New Jersey Transit, New Jersey Transit passengers',
     'Roberto Mata, Peter LoDuca, Steven A. Schwartz', 'People with eating disorders', 'Jordanians in poverty',
     'Donald Trump, Anthony Fauci', 'fast food job applicants, Amanda Claypool', 'social media users',
     'Oriana Albornoz, George Floyd protest participants', 'Derrick Ingram, Black Lives Matter activists',
     'truck drivers, Tesla drivers, David Clough', 'publishing editors, publishers',
     'San Francisco emergency services, ambulance patient',
     'General public, Gannett, Student athletes, Newspapers relying on Gannett',
     "Retool employee who was the victim of the unknown hacker, Retool, Google, 27 of Retool's clients",
     'Anonymous student', 'Authors, Amazon Customers, Amazon',
     'Potentially exploited groups, General public, Consumers', 'Journalistic integrity, General public',
     'Women, Underrepresented genders, General public, Advertisers',
     'Subaru, Major brands whose advertisements were found on these sites, GNC, General public, Citigroup',
     'Nicholas Clayton, Misty McGraw, Manuel Clayton, Illinois residents, Amy Newton, Amanda Curry',
     'Ukraine, News media in Latin America, Journalistic integrity, General public',
     "people with autism, lawyers and other experts who were not informed of the tool's limitations, Individuals assessed as high-risk based on the flawed criteria, General public",
     'General public, Journalists', 'Randal Reid, Minorities, Black people', 'UK Labour Party, Keir Starmer',
     'Ukraine, General public, European public, Democracy, American public',
     'Disabled people, Elderly people, Low-income people, Larkin Seiler, Tammy Dobbs',
     'Children (faces used in deepfakes), Victims of child sexual abuse (bodies used in videos), General public',
     'Unnamed victims in Almendralejo', 'The Guardian, Family of Lilie James',
     'General public, Journalistic integrity, News sources',
     "James Guthrie, James Guthrie's co-authors, Parliament of Australia, KPMG, Deloitte",
     "Zachariah Crabill's client, Zachariah Crabill, Legal system",
     'General public, Readers of Sports Illustrated, Journalistic integrity', 'Tesla workers, Tesla engineer',
     'Michael Cohen, David M. Schwartz', 'LAION, Various people, Various organizations, General public, Children',
     'Trisha Yearwood, Taylor Swift, Selena Gomez, Ree Drummond, Oprah, Martha Stewart, Le Creuset, Lainey Wilson, Joanna Gaines, Jennifer Lopez, General public, Fans, Blake Shelton',
     'President Joe Biden, New Hampshire voters, Kathy Sullivan, Democracy', 'Harvey Murphy Jr',
     'Ashley Beauchamp, DPD', 'Unnamed multinational company, Unnamed finance employee',
     'General public, Chicago Residents, Chicago Minority Communities', 'Hans von Ohain, Erik Rossiter',
     'Individual professionals on LinkedIn, Global defense companies, Cybersecurity firms, Cryptocurrency exchanges',
     'Voters in Pakistan, PTI (Pakistan Tehreek-e-Insaf), Imran Khan, Democracy',
     'General public, British voters, British Labour Party, Keir Starmer, Democracy',
     'Public discourse integrity, General public, Democracy, African-American voters, Black voters',
     'Classmates of two unnamed middle school boys', 'Investors',
     'Journalism, Ukraine, Oleksiy Danilov, Kyrylo Budanov', 'ChatGPT users, Chase Whiteside',
     'Palestinians, Mosab Abu Toha, Gazans', 'celebrities, British public figures, Cathy Newman',
     'U.S. voters, Taiwanese voters, General public, Election integrity, Democracy', 'Te Ani Solomon, Māori Community',
     'Maia Sandu, Presidency of Moldova, Government of Moldova, Democracy, General public',
     'Indonesian electorate, Electoral integrity, Democracy',
     'Rana Atif, Raja Bashara, Naeem Haider Panjutha, Imran Khan', 'Palestinians, Gazans',
     'Yoon Suk-yeol, Korean voters, Journalism, Electoral integrity, Democracy',
     'Ferdinand Marcos Jr., Government of the Philippines, Philippines, General public', 'General public, minors',
     'Investors, General public, Bill Ackman, Cathie Wood, Steve Cohen, Peter Lynch, Ray Dalio, Peter Bourget',
     'Kari Lake, General public, Journalism, Democracy', '',
     'Public discourse integrity, Political integrity, General public, Donald Trump',
     'Taiwanese voters, Lai Ching-te, Electoral integrity, Democratic Progressive Party, Democracy',
     'Political candidates targeted by deepfakes, Indian electorate, India, Democracy',
     'Indian electorate, Indian voters, Democracy, Electoral integrity, Media discourse, M. Karunanidhi, J. Jayalalithaa',
     'Voters, Public trust, Political figures, General public, Electoral integrity, Democracy, Civic society',
     'Eric Eiswert, Pikesville High School, Pikesville High School students and staff, Baltimore County Public Schools community',
     'General public, OpenAI, Perplexity AI', 'noyb, Max Schrems, General public',
     'Elizabeth Warren, MSNBC, Republicans, Democrats, Democracy, Election integrity, General public',
     'General public, Journalism, Democracy', 'Kim Reynolds, Donald Trump',
     'General public, Democracy, Black Americans, African-American voters',
     'Olga Loiek, Michel Janse, Lana Smalls, Carrie Williams, Shadé Zahrai',
     'Google Books, Google Ngram Viewer, Researchers, General public', 'General public, People seeking medical advice',
     'Asian People, Interracial couples, General public', 'Breeze Liu', 'Scarlett Johansson', 'minors, General public',
     'General public, People susceptible to radicalism', 'Sara, Home Bargains customers, General public',
     'Shaun Thompson, General public', 'Google users, General public',
     'Joe Biden, Democratic Party, Democracy, Election integrity, Information integrity',
     'Ron DeSantis, Elon Musk, George Soros, Klaus Schwab, Dick Cheney', 'small businesses, Advertisers',
     'Donald Trump', "Ron DeSantis, Ron DeSantis's presidential campaign",
     'Veterans, Survivors of military sexual trauma, Female veterans',
     'Facebook users, Facebook users in online support communities',
     'Journalism, Information integrity, General public, American citizens',
     'Matthew Miller, Department of State, Biden administration',
     'Joe Biden, Texas citizens, Texas officials, General public',
     'Legal professionals, Clients of lawyers, Legal system',
     'students, Turkish YKS exam takers, Turkish educational institutions',
     'small businesses, Small business customers, Small business employees, Bee Cups, Darn Tough Vermont, Jim Carter',
     'Unnamed Fullerton police officer, Fullerton Police Department',
     'Roberto Spinelli, Genoa Prosecutor’s Office, Giovanni Toti, Paolo Emilio Signorini, Italian general public',
     'Unnamed Manchester litigant, Manchester court system, General public',
     'Auschwitz Memorial Museum, Survivors of Holocaust victims, General public',
     'Tesla drivers, Drivers, General public',
     'Kristen Gonzalez, Clyde Vanel, New York lawmakers, Meta, Facebook users',
     'Ukraine, Joe Biden, General public, Biden administration',
     'New York City small business owners, New York City landlords and tenants, New York City employers and employees, Eric Adams administration',
     'Australian general public',
     'Louise Walker, Residents of Brookdale facilities, Families of residents of Brookdale facilities, Staff members of Brookdale facilities',
     'Website owners, Website operators, Ernie Smith', 'YouTube creators, General public, Content creators',
     'X (Twitter) users, Israelis, Iranians, General public', "Paul Vallas, Paul Vallas's campaign, Chicago voters",
     'students, Professors, Community colleges, Academic staff', 'General public, Catholics',
     'Instagram users, Instagram sellers, Children',
     'University hiring committees, University faculty, Scopus, Academic journals, University job candidates',
     'Individuals coerced into criminal activities, Financial fraud victims, Human trafficking victims',
     'Unnamed pedestrian',
     'Ukrainian general public, Joe Biden, General public, Democratic institutions, Biden presidential campaign, American conservatives',
     'Paul Skye Lehrman, Linnea Sage, Voice Actors',
     'Chinese-speaking users of ChatGPT, Researchers, OpenAI, OpenAI users',
     'Indian voters, General public misled by deepfake content, Political integrity and election fairness, Democracy, Truth',
     'Developers and businesses incorporating AI-suggested packages, Alibaba',
     'Individuals with speech impairments, Users whose speech is misinterpreted by Whisper, Professionals relying on accurate transcriptions, General public',
     'Privacy-conscious individuals, People with poor credit scores, Lower-income workers, Drivers unaware of data collection, Consumers affected by insurance rates, Life360 users, MyRadar users',
     'Western democracies, Volodymyr Zelenskyy, Ukraine, Secret Service, Researchers, Media consumers, General public, Electoral integrity, AI companies facing reputational damage',
     'Bank customers', 'internet users, Organizations, Individuals targeted by malware']
aaaaa=[ 'Facebook users', 'Tesla drivers', 'Women, Minority Groups', 'General public', 'unknown', 'Microsoft', 'Motorists',
     'Black people', 'Women', 'Minority Groups', 'internet users', 'Uber drivers', 'ChatGPT users', 'minors',
     'Children', 'patients', 'Twitter Users', 'Accused People', 'Amazon Customers', 'email users', 'pedestrians',
     'Amazon users', 'Facebook users having posts about painful events, Facebook users', 'Jewish people', 'Bing users',
     'San Francisco firefighters, San Francisco Fire Department', 'TikTok users', 'public figures, celebrities',
     'Google users', 'Navya, Keolis North America, bus passengers', 'Elaine Herzberg, pedestrians',
     'Starbucks employees', 'Robotics Consultant', 'Airplane Passengers, Airplane Crew', 'pedestrians, Motorists',
     'Gmail Users', 'Wikimedia Foundation, Wikipedia Editors, Wikipedia Users', 'People with Twins', 'Asian People',
     'Apple, Device Owners', 'Oliver Haberstroh, Neighbors', 'Fire Victims', 'Dong Mingzhu', 'Medical Residents',
     'Yandex Users', 'Individual Kaggle Competitors', 'drivers in Jokkmokk, drivers in Sweden, Volvo', 'Carollers',
     'Child', 'Ramji Lal', 'People with Dark Skin', 'Store Patrons', 'Oakland Residents', 'Knightscope', 'Joshua Brown',
     'Alex Harker', 'my_handy_design', 'Australian welfare recipients', 'OpenAI', 'DAO Token Holders',
     'Mountain View municipal bus passengers, Mountain View municipal bus',
     'Chinese Communist Party, Tencent Holdings, Microsoft, Turing Robot',
     'unnamed Palestinian Facebook user, Palestinian Facebook users, Arabic-speaking Facebook users, Facebook users',
     'Facebook users, Facebook users interested in COVID information, Facebook users interested in the US Presidential Election',
     'International Baccalaureate students', 'Jewish people, Google Images users',
     'non-white neighborhoods, communities of color', 'Jewish people, Jewish public figures',
     'patients of minority groups, low-income patients, female patients, Hispanic patients, patients with Medicaid insurance',
     'Leaving Certificate exam takers, Irish Department of Education and Skills',
     'Robert Julian-Borchak Williams, Black people in Detroit', 'job applicants using HireVue, HireVue customers',
     'New York City low-income communities', 'Stanford Medical frontline workers, Stanford Medical residents',
     'Buenos Aires children', 'YouTube users',
     'Facebook users, Facebook users interested in the Lekki Massacre incident',
     'Facebook users of minority groups, non-American-born Facebook users, non-Christian Facebook users, Facebook users interested in accessibility, Facebook users interested in Hispanic culture',
     'Cogo Guebara, unnamed woman injured in the fight', 'Houston Independent School District teachers',
     'livestream viewers', 'Black patients, African-American patients', 'dark-skinned people, dark-skinned women',
     'Apple Card female users, Apple Card female credit applicants',
     'Deliveroo workers with legitimate reasons for cancelling shifts, Deliveroo workers',
     'Amazon Flex employees, Amazon Flex drivers',
     'California low-income neighborhoods, California communities of color',
     'Korean Facebook Messenger users, Korean people of gender minorities, Korean people with disabilities',
     'Genderify customers, gender minority groups', 'Jovani Maldonado, Benjamin Maldonado, California public',
     'Dutch Tax Authority, Dutch families', 'Twitter Users, Twitter non-white users, Twitter non-male users',
     'Troy residents, Troy Police Department, Syracuse residents, Syracuse Police Department, San Francisco residents, San Francisco Police Department, San Antonio residents, San Antonio Police Department, New York City residents, New York City Police Department, Fall River residents, Fall River Police Department, Chicago Residents, Chicago Police Department',
     'Lucie Inland', 'Amazon delivery drivers, Amazon workers', 'Reddit users',
     'Arkansas Medicaid waiver program beneficiaries, Arkansas healthcare workers',
     'Lamya Robinson, Black Livonia residents', 'Rekognition users, arrested people', 'Uyghur people',
     'Xsolla employees', 'Black college students, Latinx college students, indigenous students', 'Libyan soldiers',
     'Black people, Facebook users', 'Muslims', 'University of Toronto BIPOC students',
     'Moshe Har Shemesh, Israeli people having tax fines',
     "internet users with disabilities, web accessibility vendors' customers",
     'Facebook users, Facebook content creators', 'California bar exam takers, flagged California bar exam takers',
     'Gilberto Alcazar Lopez, Maria Guadalupe Nieves-Lopez', 'Amazon fulfillment center workers',
     'University of Illinois students of color, University of Illinois students',
     'TikTok users, TikTok users under 18 years old', 'TikTok users, TikTok content creators',
     'Antonio Radic, YouTube chess content creators, YouTube users',
     "Kristin Livdahl's daughter, Amazon Echo customers, children using Alexa", 'SoftBank',
     'female Facebook users, Black Facebook users, male Facebook users',
     'Facebook users, LinkedIn users, YouTube users, Twitter Users, Netflix users',
     'TikTok content creators of marginalized groups', 'Sennett Devermont, Beverly Hills citizens',
     'Fuzhou Zhongfang Marlboro Mall goers', 'news sites',
     'University of Texas at Austin PhD applicants of marginalized groups',
     'Google Maps users traveling in Sierra Nevada, Google Maps users traveling in the mountains',
     'Paula Knight, Bath officials, UK public', 'San Francisco city government', 'sepsis patients',
     'people attempting suicides', 'Facebook users of small language groups, Twitter users of small language groups',
     'Amazon workers, Amazon delivery drivers', 'Target customers',
     'Facebook users of disabilities, adaptive fashion retailers', 'Hong Kong bank manager', 'inmates of color',
     'people having non-Caucasian facial features', 'Zillow Offers staff, Zillow', 'Black patients',
     'LGBTQ people, LGBTQ people of color, non-American LGBTQ people', 'Jade Thirlwall, Leigh-Anne Pinnock',
     'Facebook users of minority groups, Facebook users', 'UK ETS past test takers, UK ETS test takers, UK Home Office',
     'Natural Cycles users, Women',
     'Rohingya people, Rohingya Facebook users, Myanmar public, Facebook users in Myanmar, Burmese-speaking Facebook users',
     'Ocado', 'Eric Horvitz, Tesla drivers', 'Amaya Ross, Black students, Black test-takers',
     'Oregon State University, freight train crew', 'São Paulo Metro users, São Paulo citizens',
     'Pasco residents, Pasco Black students, Pasco students with disabilities', 'LinkedIn users',
     'Malaysian convicted people', 'unnamed Australian telecommunications company', 'Tinder users over 30 years old',
     'Korean public', 'Black WeChat users', 'Cruise vehicle', 'trans women, women of color',
     'Cruise vehicles, Cruise driver employee', 'Doctors, COVID patients',
     'Volodymyr Zelenskyy, Ukrainian social media users, Ukrainian public', 'San Francisco public, Cruise customers',
     'Tesla owner, Vision Jet owner', 'sex workers, Airbnb users', 'small businesses on Facebook',
     "unnamed UK-based energy firm's CEO", 'Spanish victims of gender violence', 'road engineer',
     'underrepresented groups, Minority Groups',
     'American physicians, American pharmacists, American patients of minority groups, American patients',
     'Google Docs users', 'Shophie Wilmès, Belgian government', 'Zhihu employees, Chinese tech workers',
     'Black students', 'fair visitors', 'Target, Target customers', 'TikTok users, TikTok new users',
     'delivery truck, pedestrians, Tesla drivers', 'Ever AI users',
     'Instagram users, Snapchat users, American social media users',
     'Salta teenage girls, Salta girls of minority groups', 'Naver customers', 'rhinos in conservation',
     'people with disabilities', 'Facebook content moderators', "pseudonymous Estée Lauder's former staff",
     'XPeng Motors customers', 'Pakistani citizens', 'Honolulu homeless people', 'John Bernal, San Jose public',
     'Ukrainian social media users', 'Ping An customers, Chinese minority groups', 'Thoughts users, Twitter Users',
     'Hive Box customers', 'WeChat Pay users', 'students, low-income minority students, Teachers',
     'oncologists, cancer patients', 'Yoshihiro Umeda, pedestrians, Tesla drivers', 'Umesh Ramesh Dhake',
     'Jeremy Beren Banner, Tesla users', 'Mark Molner', 'Gao Yaning, Tesla drivers', 'Brian Hofer',
     'Intellectual Property rights holders', 'Indian voters, Indian social media users, Indian women journalists',
     'tourists, Waze users', 'YouTube users, YouTube content creators', 'the Gilliam family',
     'Tumblr content creators, Tumblr users', 'tourists, Apple Maps users', 'Denise Green', 'Los Gatos residents',
     'children of minority groups, families of minority groups',
     'Sherman Oaks residents, Waze users, Los Angeles city government', 'child named Christopher',
     'Twitter, Twitter Users, Twitter users participating in COVID-19 discussions',
     'Landon Embry, motorcyclists, Tesla drivers', 'small businesses on Amazon, Amazon Customers',
     'FaceApp non-binary presenting users, FaceApp transgender users, FaceApp users', 'internet social platform users',
     'Chicago drivers', 'unnamed property owner', 'The Good Guys customers, Kmart customers, Bunnings customers',
     'UK drivers', 'non-TPI-registered Grab drivers, Grab drivers in Indonesia, Grab drivers',
     'US naturalized citizens, US immigrants, US citizenship applicants, US immigration applicants',
     'San Francisco homeless people',
     'Renren, Buding Movie Tickets, Yi Xia, Dangdang, Chinese startups, Chinese companies',
     'victims of crimes documented on social media, investigative journalists, International Criminal Court investigators, International Court of Justice investigators, criminal investigators',
     'Michael Williams', 'Replika users, Replika male users, Replika',
     'San Francisco traffic participants, San Francisco public', 'Uyghur people, Turkic Muslim ethnic groups',
     'Google Photos users residing in Illinois, Google Photos users, Illinois residents',
     'Virginia convicted felons, Virginia Black offenders, Virginia young offenders',
     'social media users, Instagram users, Facebook users',
     'neighborhoods of color, Brown communities, Black communities, Adam Toledo', 'US schools, US students',
     'Minority Groups, underrepresented groups', 'YouTube young male users, YouTube male users, Caleb Cain',
     'Pa Edrissa Manjang, Uber Eats Black delivery drivers', 'Jewish people, BlenderBot 3 users',
     'Facebook users sharing photo evidence of slavery, Facebook users', 'Google Lens users',
     'Cruise passengers, Toyota Prius passengers', "Olivia Solon, Olivia Solon's Facebook connections",
     'You You Xue, Tesla drivers', 'Nabla customers', 'Ousmane Bah, NYC Black people, NYC Black young people',
     'Tesla drivers, Culver City Fire Department', 'UK visa applicants from some countries',
     'Silicon Valley traffic participants, Silicon Valley residents',
     'TikTok male teenager users, TikTok male users, TikTok teenage users, TikTok users, TikTok',
     "Derrick Monet, Jenna Monet, the Monets' family", 'Black women, Black people, Google users',
     'Japanese pornographic actors', 'Laguna Beach Police Department', 'Facebook users, Twitter Users, YouTube users',
     'Waymo passengers', 'police investigators',
     'California Department of Motor Vehicles, Tesla customers, California residents',
     'Coffee Meets Bagel users having no ethnicity preference, Coffee Meets Bagel users',
     'local law enforcement officers', 'YouTube users, YouTube climate-skeptic users',
     'unnamed Tesla driver, Tesla drivers', 'Henn na Hotel guests, Henn na Hotal staff', 'The Vindicator',
     'job candidates using MyInterview, job candidates using Curious Thing, employers using MyInterview, employers using Curious Thing',
     'YouTube users skeptical of US election results', '15.ai, 15.ai users', 'Honda customers',
     'Nissan drivers, traffic participants', 'unnamed woman passenger',
     'The Seed Company by E.W. Gaze, businesses on Facebook', 'Bucheon citizens',
     'Sunnyside beachgoers, Marie Curtis beachgoers, Toronto citizens',
     'Twitter left-leaning politicians, Twitter left-leaning news organizations, Twitter left-leaning users, Twitter Users',
     'Marietje Schaake', 'unnamed 22-year-old male driver, Tesla drivers', 'Instagram users',
     'William Varner, unnamed passenger',
     "Lalani Erika Renee Walton, Arriani Jaileen Arroyo, Lalani Erika Renee Walton's family, Arriani Jaileen Arroyo's family, TikTok young users, TikTok users",
     'iPhone Face ID users, iPhone X Face ID users', 'Notting Hill Carnival goers',
     'students at Charlotte Mecklenburg Schools, teachers at Charlotte Mecklenburg Schools, security officers at Charlotte Mecklenburg Schools',
     'Women of Sex Tech conference attendants, Women of Sex Tech conference organizers',
     'Facebook users posting legitimate COVID-19 news, Facebook users', 'Instagram users, Facebook users',
     'a software engineer named Mark, parents using telemedicine services',
     'Teachers, non-cheating students, cheating students',
     'Marcus Rashford, Jadon Sancho, Bukayo Saka, Facebook users, Instagram users, Twitter Users',
     "Sirey Zhang, Geisel School of Medicine's students, Geisel School of Medicine's professors, Geisel School of Medicine's accused students",
     'FInals attendees, falsely accused Finals attendees', "Walter Huang's family, Walter Huang",
     'museums on Facebook, Facebook users interested in arts, Facebook users', 'TheFaceTag app users',
     'TikTok young users, TikTok users',
     'call center agents having non-Midwestern-American accent, people having non-Midwestern-American accent',
     'unnamed Tesla owner, Tesla drivers', 'Stability AI, deepfaked celebrities', 'Connecticut State Police', 'none',
     'Russian pornographic actresses, Russian sex workers', 'YouTube young users, YouTube users', 'Nijeer Parks',
     'Jisuk Mok, Frisco residents', 'vehicle repair shops, vehicle owners', 'unnamed Florida teenager',
     'UK immigrant newlyweds', 'Halle Bailey, Black actresses', 'historically disadvantaged groups',
     "Google's competitor shopping services", 'TuSimple, State of Arizona',
     'Facebook users posting about Plymouth Hoe, Facebook users in Plymouth Hoe, Plymouth Hoe residents',
     'women in need of abortion services, women having unexpected or crisis pregnancies',
     'unemployed Michigan residents falsely accused of fraud, unemployed Michigan residents', 'apartment renters',
     "Danielle's family, Amazon Echo users", 'Weibo, Chinese government', "Jeremy Banner, Jeremy Banner's family",
     'Black Google Home Mini users, Google Home Mini users', "Sebastian Galassi, Sebastian Galassi's family",
     'transgender Uber drivers', 'Stephan de Vries', 'Filipinos', 'the Karnataka government, Kannada speakers',
     'poor neighborhoods, neighborhoods of color',
     'students, Rock Hill School students, Pinecrest Academy Horizon students',
     'Transgender YouTubers, transgender people',
     'young men having credit scores, people scored on old scoring versions, people changing addresses frequently',
     'political organizations, political candidates', 'Twitter Users, Twitter',
     'Finland National Bureau of Investigation', 'Xi Jinping, Aung San Suu Kyi',
     'Real Women in Trucking, older female blue-collar workers', 'low digitally skilled Facebook users',
     'Uber drivers in India', 'digital artists, artists publishing on social media, artists',
     "victims of FTX's collapse, Twitter Users", 'women using Lensa AI, Asian women using Lensa AI',
     'Canadian students', 'XPeng driver', 'traffic participants, emergency vehicles, Cruise passengers, Cruise',
     'HSBC UK customers, Dan Simmons', 'Silvon Simmons', 'Kelly Conlon, Alexis Majano', 'Airline Passengers',
     'low-income communities, communities of color, Black Chicago residents', 'traffic participants, Tesla drivers',
     'Coupang suppliers, Coupang customers', 'traffic participants',
     'small businesses in India, Amazon customers in India', 'Michael Oliver, Black people in Detroit',
     'travelers in Korean airports', 'US Air Force, UK Royal Air Force, Kevin Main, David Williams',
     'mass shooting victims, Durham residents, Durham Police Department', 'Twitch users, Vedal',
     'research participants, Koko customers', 'Kenyan Sama AI employees', 'Getty Images, Getty Images contributors',
     'Replika users', 'plagiarized entities, CNET readers',
     'San Francisco residents, San Francisco firefighters, San Francisco Fire Department',
     'Apple Watch users doing winter activities, ski patrols, emergency dispatchers',
     'people having medical photos online', 'LinkedIn users, Instagram users, Facebook users', 'OpenAI, Microsoft',
     'racial minorities', "McDonald's customers", 'Walmart employees',
     'gender minority groups, racial minority groups, underrepresented groups in training data',
     'Palestinians residing in the West Bank', 'Souther Co-op customers', 'political opposition in Uganda',
     'Facebook users speaking Swahili, Facebook users speaking English, Facebook users',
     'Chinook Centre mall goers, Market Mall goers',
     'artists submitting in the digital arts category, digital artists, artists', 'Amazon delivery drivers',
     'SIT Acronis Autonomous', 'A-level pupils, GCSE pupils, pupils in state schools, underprivileged pupils',
     "OpenAI, people having personal data in GPT-2's training data", 'Black residents in Edmonton',
     'Black people in Brazil, Black people in Bahia',
     'interviewers of remote-work positions, employers of remote-work positions',
     'YouTube content creators, Twitch content creators, TikTok content creators, Instagram content creators',
     'WNY Gardeners, gardening Facebook groups, Facebook users in gardening groups',
     'Palestinian social media users, Facebook users, Instagram users, Twitter Users, Facebook employees having families affected by the conflict',
     'Google Pixel 6a users', 'Thai citizens, elder Thai citizens',
     'Molly Rose Russell, the Russell family, teenage girls, teenagers', 'Amazon warehouse workers',
     'young TikTok users, TikTok users, Gen Z TikTok users', 'Tesla drivers, horse-drawn carriages',
     'Minority Groups, Meta AI, Meta, Facebook, Minority Groups', 'Latitude',
     "Shannon Carpenter, McDonald's customers residing in Illinois, McDonald's customers",
     'Facebook users speaking East African languages, Facebook users in East Africa',
     "pseudonymized psychiatrist's patients, pseudonymized psychiatrist, patients, healthcare providers",
     'sex workers using Facebook', 'Stack Overflow users, Stack Overflow',
     'live-stream ceremony viewers, King Maha Vajiralongkorn', 'ChatGPT users, OpenAI', 'Black State Farm customers',
     'gay men in New York City, Julio Ramirez', 'foreign journalists in Henan, international students in Henan',
     'Black people in Louisiana, Randall Reid', "US Navy, Nathan White's family, Nathan White",
     'Spanish-speaking Instagram users', 'Immunefi', 'CNET readers', 'Frauke Zeller, David Harris', 'Black taxpayers',
     'Twitch users, transgender communities, LGBTQ communities', 'Teachers, students', 'Google, Google shareholders',
     'Tigrinya-speaking Facebook users, Facebook users in Ethiopia, Ethiopian public, Afaan Oromo-speaking Facebook users',
     'Replika users, Replika', 'victims in Paris attacks, Nohemi Gonzalez family, Nohemi Gonzalez',
     'Tesla drivers, city traffic participants, Tesla',
     'Maya Higa, female streamers, female content creators, @Sweet Anita, @QTCinderella, @Pokimane',
     'Vanderbilt University students, Vanderbilt University', 'Mohammed Khadeer',
     'Haitian asylum seekers, African asylum seekers, Black asylum seekers', 'Lloyds Bank',
     'Venezuelan people, social media users', 'Clarkesworld', "Ben Perkin's parents, Perkins family",
     'unnamed female college student', 'Twitter Users, social media users',
     'Black families in Allegheny, households with disabled people in Allegheny, Hackneys family',
     'Family and Friends of Deceased, Belgian Man', 'Brian Hood', 'Pope Francis',
     'Italian children, Italian minors', 'Starship Technologies', 'political campaigns, Facebook users',
     'Centrelink account holders',
     'Your CBD Store, University of Pittsburgh Police Department, Phillipsburg High School, Hempstead High School, Dubuque Police Department, Bellefonte Area High School',
     'Justine Hsu', 'Universal Music Group, The Weeknd, Drake', 'Uber drivers, gig workers, Amazon delivery workers',
     'Amazon', 'racial minority groups, Women, gender minority groups',
     "Facebook's children users, Instagram's children users", 'Jennifer DeStefano, DeStefanos family',
     'Texas A&M University students', 'Twitter Users, Stock Holders, Family of People Near Pentagon',
     'Kemal Kilicdaroglu, Muharrem İnce',
     'Ronald L. Haeberle, Ron Haviv, Raymond D’Addario, Lynsey Addario, Lee Miller, Larry Towell, James Nachtwey',
     'Tillman Mitchell, the Mitchells family', 'Paul Tremblay, Mona Awad, authors of copyrighted works',
     'Alexa children users', 'research grant administrators, research grant applicants',
     'internet users, Children, social media users', 'Clive Kabatznik, Bank of America',
     'Hawaiian government, General public, American government',
     'Barack Obama, Oprah Winfrey, Jamie Foxx, Joan Rivers, Phil McGraw, Yahoo! News, E! News, TikTok, General public',
     "Queen Elizabeth II, British Royal Family, British Royal Family's staff, Jaswant Singh Chail, General public",
     'Facebook Messenger users',
     'Microsoft, Microsoft employees, Third parties relying on the confidentiality of the exposed data',
     'Slovakian electorate, Monika Todova, Michal Šimečka, Democratic process in Slovakia', 'Gizmodo journalists',
     'Non-cisgender individuals, LGBTQ+ community',
     'Black men who underwent lung function tests between 2010 and 2020 and potentially received inaccurate or delayed diagnoses and medical interventions due to the biased algorithm',
     'Children, General public, minors, teenagers',
     'Children whose data was collected and used for advertising, Schools and teachers who were misinformed and burdened with COPPA compliance responsibilities without adequate disclosure',
     'Consumers relying on accurate image categorization, members of racial and ethnic minorities who risk being stereotyped or misrepresented',
     'Chris Cowell', 'Porcha Woodruff', 'Rona Wang, Racial minorities who may have experienced the same result',
     'Potential users of the Savey Meal-bot', 'pedestrians, General public', 'Unnamed female students, Francesca Mani',
     'Unnamed employee of South Gyeongsang province produce distribution center',
     'Minors Exploited in the Images, General public',
     'Wolf Blitzer, Tom Hanks, Sanjay Gupta, Sally Bundock, Robin Williams, public figures, MrBeast, Matthew Amroliwala, Jesse Waters, Ian Hanomansing, General public, Gayle King, celebrities',
     'Keir Starmer, General public, British Labour Party',
     'Medicare Advantage Plan Patients, Healthcare Providers (Doctors and Therapists), elderly patients',
     'Romanians in the United Kingdom, Greeks in the United Kingdom, Bulgarians in the United Kingdom, British public, Albanians in the United Kingdom',
     'Anonymous female high school students', 'Federal Navy Credit Union Customers',
     'Rite Aid customers who were women, Rite Aid customers who were minorities, Rite Aid customers',
     'Sikh people, President Joe Biden, Pope Francis, Navajo people, Minorities, Hillary Clinton, General public, Donald Trump',
     'General Motors, Chevrolet of Watsonville', 'Amazon, Amazon sellers, Amazon Customers',
     "George Carlin's estate, Kelly Carlin, George Carlin",
     'Krista Perry, Larissa Martinez, Jay Baron, digital artists', 'Taylor Swift, General public', 'Georgie Purcell',
     'Steve Harvey, Sean “Diddy” Combs, General public, Denzel Washington, Black celebrities, Bishop T.D. Jakes',
     'General public, Chatbot users', 'Jake Moffatt', 'Unnamed owner of tow truck', 'Bobbi Althoff',
     'Julien Fanciulli, General public, France 24', 'Bicyclist', 'Unnamed middle school students',
     'President Joe Biden, transgender people', 'Joe Rogan, Joe Rogan fans, TikTok users',
     'YouTube users, Twitter Users, Synthesia, Facebook users', 'Voice Actors',
     'Derek Mobley, applicants with disabilities, applicants over 40, African American applicants',
     'Scarlett Johansson, female celebrities, Emma Watson', 'John Piscitella', 'Jonathan Faridian, DoNotPay customers',
     'OpenAI, TaskRabbit worker', 'social media users, 2023 Turkey–Syria earthquake victims',
     'Frances Walter, elderly patients', 'Marvin von Hagen, Seth Lazar, Microsoft, OpenAI, Bing Chat users',
     'Vietnamese Facebook users', 'Lucy Goetz, high school students', 'Randal Quran Reid', 'Amazon Fresh',
     'Roomba J7 device owners in project IO, iRobot, Scale AI', 'Women, underage girls, female celebrities',
     'transgender travelers, gender-nonconforming travelers',
     'anonymous Pashto-speaking refugee, Pashto-speaking asylum seekers, Dari-speaking asylum seekers',
     'COVID-19 patients, COVID-19 healthcare providers', 'New Jersey Transit, New Jersey Transit passengers',
     'Roberto Mata, Peter LoDuca, Steven A. Schwartz', 'People with eating disorders', 'Jordanians in poverty',
     'Donald Trump, Anthony Fauci', 'fast food job applicants, Amanda Claypool', 'social media users',
     'Oriana Albornoz, George Floyd protest participants', 'Derrick Ingram, Black Lives Matter activists',
     'truck drivers, Tesla drivers, David Clough', 'publishing editors, publishers',
     'San Francisco emergency services, ambulance patient',
     'General public, Gannett, Student athletes, Newspapers relying on Gannett',
     "Retool employee who was the victim of the unknown hacker, Retool, Google, 27 of Retool's clients",
     'Anonymous student', 'Authors, Amazon Customers, Amazon',
     'Potentially exploited groups, General public, Consumers', 'Journalistic integrity, General public',
     'Women, Underrepresented genders, General public, Advertisers',
     'Subaru, Major brands whose advertisements were found on these sites, GNC, General public, Citigroup',
     'Nicholas Clayton, Misty McGraw, Manuel Clayton, Illinois residents, Amy Newton, Amanda Curry',
     'Ukraine, News media in Latin America, Journalistic integrity, General public',
     "people with autism, lawyers and other experts who were not informed of the tool's limitations, Individuals assessed as high-risk based on the flawed criteria, General public",
     'General public, Journalists', 'Randal Reid, Minorities, Black people', 'UK Labour Party, Keir Starmer',
     'Ukraine, General public, European public, Democracy, American public',
     'Disabled people, Elderly people, Low-income people, Larkin Seiler, Tammy Dobbs',
     'Children (faces used in deepfakes), Victims of child sexual abuse (bodies used in videos), General public',
     'Unnamed victims in Almendralejo', 'The Guardian, Family of Lilie James',
     'General public, Journalistic integrity, News sources',
     "James Guthrie, James Guthrie's co-authors, Parliament of Australia, KPMG, Deloitte",
     "Zachariah Crabill's client, Zachariah Crabill, Legal system",
     'General public, Readers of Sports Illustrated, Journalistic integrity', 'Tesla workers, Tesla engineer',
     'Michael Cohen, David M. Schwartz', 'LAION, Various people, Various organizations, General public, Children',
     'Trisha Yearwood, Taylor Swift, Selena Gomez, Ree Drummond, Oprah, Martha Stewart, Le Creuset, Lainey Wilson, Joanna Gaines, Jennifer Lopez, General public, Fans, Blake Shelton',
     'President Joe Biden, New Hampshire voters, Kathy Sullivan, Democracy', 'Harvey Murphy Jr',
     'Ashley Beauchamp, DPD', 'Unnamed multinational company, Unnamed finance employee',
     'General public, Chicago Residents, Chicago Minority Communities', 'Hans von Ohain, Erik Rossiter',
     'Individual professionals on LinkedIn, Global defense companies, Cybersecurity firms, Cryptocurrency exchanges',
     'Voters in Pakistan, PTI (Pakistan Tehreek-e-Insaf), Imran Khan, Democracy',
     'General public, British voters, British Labour Party, Keir Starmer, Democracy',
     'Public discourse integrity, General public, Democracy, African-American voters, Black voters',
     'Classmates of two unnamed middle school boys', 'Investors',
     'Journalism, Ukraine, Oleksiy Danilov, Kyrylo Budanov', 'ChatGPT users, Chase Whiteside',
     'Palestinians, Mosab Abu Toha, Gazans', 'celebrities, British public figures, Cathy Newman',
     'U.S. voters, Taiwanese voters, General public, Election integrity, Democracy', 'Te Ani Solomon, Māori Community',
     'Maia Sandu, Presidency of Moldova, Government of Moldova, Democracy, General public',
     'Indonesian electorate, Electoral integrity, Democracy',
     'Rana Atif, Raja Bashara, Naeem Haider Panjutha, Imran Khan', 'Palestinians, Gazans',
     'Yoon Suk-yeol, Korean voters, Journalism, Electoral integrity, Democracy',
     'Ferdinand Marcos Jr., Government of the Philippines, Philippines, General public', 'General public, minors',
     'Investors, General public, Bill Ackman, Cathie Wood, Steve Cohen, Peter Lynch, Ray Dalio, Peter Bourget',
     'Kari Lake, General public, Journalism, Democracy', '',
     'Public discourse integrity, Political integrity, General public, Donald Trump',
     'Taiwanese voters, Lai Ching-te, Electoral integrity, Democratic Progressive Party, Democracy',
     'Political candidates targeted by deepfakes, Indian electorate, India, Democracy',
     'Indian electorate, Indian voters, Democracy, Electoral integrity, Media discourse, M. Karunanidhi, J. Jayalalithaa',
     'Voters, Public trust, Political figures, General public, Electoral integrity, Democracy, Civic society',
     'Eric Eiswert, Pikesville High School, Pikesville High School students and staff, Baltimore County Public Schools community',
     'General public, OpenAI, Perplexity AI', 'noyb, Max Schrems, General public',
     'Elizabeth Warren, MSNBC, Republicans, Democrats, Democracy, Election integrity, General public',
     'General public, Journalism, Democracy', 'Kim Reynolds, Donald Trump',
     'General public, Democracy, Black Americans, African-American voters',
     'Olga Loiek, Michel Janse, Lana Smalls, Carrie Williams, Shadé Zahrai',
     'Google Books, Google Ngram Viewer, Researchers, General public', 'General public, People seeking medical advice',
     'Asian People, Interracial couples, General public', 'Breeze Liu', 'Scarlett Johansson', 'minors, General public',
     'General public, People susceptible to radicalism', 'Sara, Home Bargains customers, General public',
     'Shaun Thompson, General public', 'Google users, General public',
     'Joe Biden, Democratic Party, Democracy, Election integrity, Information integrity',
     'Ron DeSantis, Elon Musk, George Soros, Klaus Schwab, Dick Cheney', 'small businesses, Advertisers',
     'Donald Trump', "Ron DeSantis, Ron DeSantis's presidential campaign",
     'Veterans, Survivors of military sexual trauma, Female veterans',
     'Facebook users, Facebook users in online support communities',
     'Journalism, Information integrity, General public, American citizens',
     'Matthew Miller, Department of State, Biden administration',
     'Joe Biden, Texas citizens, Texas officials, General public',
     'Legal professionals, Clients of lawyers, Legal system',
     'students, Turkish YKS exam takers, Turkish educational institutions',
     'small businesses, Small business customers, Small business employees, Bee Cups, Darn Tough Vermont, Jim Carter',
     'Unnamed Fullerton police officer, Fullerton Police Department',
     'Roberto Spinelli, Genoa Prosecutor’s Office, Giovanni Toti, Paolo Emilio Signorini, Italian general public',
     'Unnamed Manchester litigant, Manchester court system, General public',
     'Auschwitz Memorial Museum, Survivors of Holocaust victims, General public',
     'Tesla drivers, Drivers, General public',
     'Kristen Gonzalez, Clyde Vanel, New York lawmakers, Meta, Facebook users',
     'Ukraine, Joe Biden, General public, Biden administration',
     'New York City small business owners, New York City landlords and tenants, New York City employers and employees, Eric Adams administration',
     'Australian general public',
     'Louise Walker, Residents of Brookdale facilities, Families of residents of Brookdale facilities, Staff members of Brookdale facilities',
     'Website owners, Website operators, Ernie Smith', 'YouTube creators, General public, Content creators',
     'X (Twitter) users, Israelis, Iranians, General public', "Paul Vallas, Paul Vallas's campaign, Chicago voters",
     'students, Professors, Community colleges, Academic staff', 'General public, Catholics',
     'Instagram users, Instagram sellers, Children',
     'University hiring committees, University faculty, Scopus, Academic journals, University job candidates',
     'Individuals coerced into criminal activities, Financial fraud victims, Human trafficking victims',
     'Unnamed pedestrian',
     'Ukrainian general public, Joe Biden, General public, Democratic institutions, Biden presidential campaign, American conservatives',
     'Paul Skye Lehrman, Linnea Sage, Voice Actors',
     'Chinese-speaking users of ChatGPT, Researchers, OpenAI, OpenAI users',
     'Indian voters, General public misled by deepfake content, Political integrity and election fairness, Democracy, Truth',
     'Developers and businesses incorporating AI-suggested packages, Alibaba',
     'Individuals with speech impairments, Users whose speech is misinterpreted by Whisper, Professionals relying on accurate transcriptions, General public',
     'Privacy-conscious individuals, People with poor credit scores, Lower-income workers, Drivers unaware of data collection, Consumers affected by insurance rates, Life360 users, MyRadar users',
     'Western democracies, Volodymyr Zelenskyy, Ukraine, Secret Service, Researchers, Media consumers, General public, Electoral integrity, AI companies facing reputational damage',
     'Bank customers', 'internet users, Organizations, Individuals targeted by malware',
     'Le Pen family, French general public', 'UK general public, UK housing benefit claimants', 'Lin (林)',
     'Single mothers, British single mothers', 'Zelda Williams, Robin Williams, Family of Robin Williams',
     'Kamala Harris, Journalism, General public, Donald Trump', 'Kevin Bankston, Google users, Google Drive users',
     'CIOs, Enterprise teams, Companies in general, Microsoft Copilot users',
     'Apple, Designers and developers using Figma’s AI tool, Figma users',
     'Volkswagen drivers, Potential passengers and road users at risk due to malfunctioning AEB systems',
     'Women in Spain, Stefany González Escarraman, Spanish general public, María, Luz, Lobna Hemid, Eva Jaular, 247 women in Spain (unnamed)',
     'Kiri Wagstaff, PayPal customer service representatives, PayPal customers',
     'Hoodline readers, Journalism, General public', 'Journalism, General public, Chatbot users',
     'An Appalachian Summer Festival attendees, OpenAI',
     "Bridget Todd, Bridget Todd's family, Chris Mohney, Chris Mohney's family, Bereaved families",
     'Dave Fanning, BNN Breaking readers, Journalism, General public',
     'Stella Creasy, Priti Patel, Penny Mordaunt, Gillian Keegan, Dehenna Davison, Angela Rayner',
     'Olena Zelenska, Volodymyr Zelensky, Ukrainian government, Ukrainian general public, European Union general public',
     'Truth, Kamala Harris, Joe Biden, General public, American voters', 'ChatGPT macOS users',
     'Instagram users, Facebook users, Elijah Ott', 'Sabrina Javellana', 'Warehouse Workers', 'Teachers', 'Researchers',
     'Delphi Technologies', 'female applicants', 'Alexa Device Owners', 'USC Information Sciences Institute',
     'Ibrahim Diallo', 'Market Participants', 'Barack Obama', 'Tesla', 'Varied', 'Video Game Players',
     'Delhi Metro Rail Corporation', 'All Life on Earth', 'United States Government',
     'Taylor Swift, Nintendo, Kamala Harris, Joe Biden, Donald Trump, Disney, Alexandria Ocasio-Cortez']


def unique_elements(list1, list2):
    # 将两个列表转换为集合，利用集合的差集找出不重复的元素
    print(len(list1))
    print(len(list2))
    unique_in_list1 = set(list1) - set(list2)
    unique_in_list2 = set(list2) - set(list1)

    # 合并两个差集的结果
    result = list(unique_in_list1.union(unique_in_list2))

    return result
print(unique_elements(aaa,aaaaa))