issues_incidents = \
    [
    "Misinformation",
    "Algorithm Bias",
    "Deepfake",
    "Privacy",
    "Facial Recognition",
    "Autopilot safety",
    "Privacy Violation",
    "Algorithmic Bias",
    "Disinformation",
    "Content Moderation",
    "Autonomous Vehicles",
    "Discrimination",
    "Safety",
    "Bias",
    "Ethics",
    "Deepfakes",
    "Cybersecurity",
    "Racial Bias",
    "Ethical Concerns",
    "Gender Bias",
    "AI Ethics",
    "Security",
    "Deepfake Video",
    "Technology",
    "Facial Recognition Bias",
    "Deepfake technology",
    "Vehicle Safety",
    "Deepfake Technology",
    "Ethical concerns",
    "Workplace safety",
    "racial bias",
    "Translation error",
    "Facial Recognition Error",
    "Content moderation",
    "Privacy violation",
    "Misidentification",
    "Academic Integrity",
    "Copyright infringement",
    "AI-generated content",
    "Deepfake Pornography",
    "Gender bias",
    "Censorship",
    "Autonomous Driving",
    "Teacher Evaluation",
    "Algorithm Discrimination",
    "Workplace Safety",
    "Robot Malfunction",
    "Autopilot malfunction",
    "Misrepresentation",
    "Data Breach",
    "Data Privacy",
    "Privacy concerns",
    "Surveillance",
    "Scam",
    "Scams",
    "Child safety",
    "Facial recognition",
    "Racial Discrimination",
    "Racial Profiling",
    "Police Technology",
    "AI ethics",
    "Algorithmic Discrimination",
    "Child Safety",
    "Copyright Infringement",
    "Hate Speech",
    "Accident",
    "Self-driving technology",
    "Law Enforcement Error",
    "Impersonation",
    "Social Media Manipulation",
    "Navigation error",
    "Algorithm Error",
    "Surveillance Technology",
    "Translation Error",
    "Product recommendation",
    "Propaganda",
    "Self-Driving Technology",
    "Intellectual Property",
    "Academic misconduct",
    "Autopilot Safety",
    "Antitrust",
    "Autonomous Vehicle Safety",
    "Automated Moderation Error",
    "Privacy breach",
    "Hate speech",
    "Deepfake Scam",
    "Technology Failure",
    "Plagiarism",
    "Autopilot technology",
    "AI moderation",
    "Misuse of AI",
    "Child Exploitation",
    "Healthcare",
    "Online Scams",
    "AI Chatbots",
    "Quality Control",
    "Facial Recognition Technology",
    "Deepfake Misinformation",
    "AI Error",
    "Data Security",
    "Robotic Surgery Malfunctions",
    "Scheduling Algorithm",
    "Tesla Autopilot Crashes",
    "Biased Sentiment Analysis",
    "Racial bias",
    "Aircraft safety",
    "Sexism and Racism",
    "Vandalism Prevention",
    "security",
    "Product malfunction",
    "Matching Program Inefficiencies",
    "Overfitting",
    "Customer Service",
    "Predictive Policing Biases",
    "Autonomous Driving Safety",
    "AI error",
    "Counterfeit products",
    "Automated Debt Assessment",
    "Reinforcement Learning",
    "Self-driving car technology",
    "inappropriate content",
    "Chatbot programming",
    "Education system",
    "Anti-Semitism",
    "Search Engine Bias",
    "Education",
    "Facial Analysis",
    "Autopilot",
    "Vaccine distribution",
    "Radicalization",
    "Housing discrimination",
    "Robot Responsiveness",
    "Algorithm bias",
    "Automated Dismissals",
    "Equity",
    "ShotSpotter reliability",
    "Robo-debt",
    "AI Bias",
    "Healthcare Allocation",
    "Employee Privacy",
    "Race-based admissions",
    "Military Technology",
    "Biometric data privacy",
    "Transparency",
    "Web Accessibility",
    "Proctoring Algorithm",
    "Proctorio's Remote-Testing AI",
    "Ethical Bias",
    "AI Misinterpretation",
    "Popularity Bias",
    "Online Harassment",
    "Navigation",
    "Technology Error",
    "Driverless Testing",
    "Algorithm Accuracy",
    "Product recommendations",
    "Driver Safety",
    "Advertisement Moderation",
    "Fraudulent Impersonation",
    "Predictive Pricing Accuracy",
    "Privacy Concerns",
    "Hate Speech Detection",
    "Voice Recognition Evidence",
    "Contraceptive App",
    "Warehouse Safety",
    "Predictive Policing",
    "Political Ad Detection",
    "Fake Profiles",
    "Judicial Algorithm",
    "Incident Management",
    "Age discrimination",
    "Racism",
    "Traffic violation",
    "autonomous vehicles",
    "AI Tools",
    "Algorithm Transparency",
    "Autonomous Vehicle Incident",
    "Trustworthiness Algorithm",
    "Algorithmic moderation",
    "Fraud",
    "Road Safety",
    "Inclusive Language Feature",
    "Misleading Technology Performance",
    "Phantom Braking",
    "Algorithm Failure",
    "Algorithm Manipulation",
    "Poaching",
    "Working Conditions",
    "Biometric ID Compromise",
    "Disinformation Campaign",
    "Ethical AI",
    "Facial Recognition Security",
    "Medical Technology",
    "Road safety",
    "Navigation Error",
    "Traffic Routing",
    "Traffic Safety",
    "Gender Prediction",
    "Legal",
    "Unfair Competition",
    "Immigration Vetting Software",
    "Homelessness",
    "App Store Ranking",
    "Content Removal",
    "Unreliable Evidence",
    "School Shootings",
    "Inappropriate Content",
    "AI in healthcare",
    "Facial Misidentification",
    "Algorithm Abuse",
    "Obscenity Law Violation",
    "False Advertising",
    "Algorithmic Recommendations",
    "Hiring Algorithms",
    "Water Quality",
    "Car accident",
    "Social media influence",
    "Face ID malfunction",
    "False Positives",
    "Anti-Spam Filter",
    "Automated Detection Error",
    "Online Hate Speech",
    "Algorithmic Content Moderation",
    "Robot Safety",
    "Ad fraud",
    "Wrongful Arrest",
    "Insurance Estimation",
    "racial representation",
    "Wrongful Accusations",
    "Access to Abortion Services",
    "Unemployment Benefits",
    "Antitrust behavior",
    "GDPR violation",
    "racism",
    "Employee Treatment",
    "Transgender Discrimination",
    "Promotion Error",
    "Cultural Insensitivity",
    "Credit Scoring",
    "Email Sorting",
    "Insensitive promotion",
    "Racial Injustice",
    "Flight Delays",
    "Autopilot misuse",
    "Antitrust Violation",
    "Friendly Fire",
    "Ethical labor practices",
    "Sexual Harassment",
    "Factual Accuracy",
    "AI technology",
    "Worker Safety",
    "Bias in AI",
    "AI Art",
    "Privacy Rights",
    "Grade Standardization",
    "Security Vulnerability",
    "Facial Recognition Errors",
    "Online Harm",
    "Employee Monitoring",
    "Traffic obstruction",
    "Incorrect Answers",
    "Moderation Failure",
    "Content Filtering",
    "Identity Theft",
    "Military technology error",
    "Bug Reports",
    "Robot Destruction",
    "safety",
    "Transphobia",
    "AI Text Detection",
    "AI behavior changes",
    "YouTube Recommendations",
    "Accuracy",
    "Communication",
    "Police brutality",
    "False accusation",
    "Date Confusion",
    "Facial Recognition Misuse",
    "Political Polarization",
    "Algorithmic Influence",
    "Algorithmic Pricing",
    "Algorithm Misinformation",
    "Deepfakes and Disinformation",
    "CAPTCHA bypass",
    "Confidentiality breach",
    "Voice Deepfake",
    "Security Threat",
    "Data Exposure",
    "Deepfake Influence",
    "Stereotyping",
    "Child Sexual Abuse Content",
    "Racial Bias in Image Recognition",
    "Insurance Denials",
    "Safety concerns",
    "Deepfake Images",
    "Child exploitation",
    "Nationality-based targeting",
    "Product Naming",
    "Unauthorized Impersonation",
    "Art Theft",
    "Image manipulation",
    "Software Flaw",
    "Nonconsensual Deepfake Porn",
    "Glitch",
    "Data Protection",
    "Cyberbullying",
    "Deepfake Porn",
    "Autonomous Driving Technology",
    "Methodological Flaws",
    "Storm Surge",
    "Pedestrian Safety",
    "Social Welfare Distribution",
    "Sextortion",
    "Artificial Intelligence",
    "AI-generated art",
    "AI-Generated Content",
    "AI-generated content accuracy",
    "Gender Discrimination",
    "Disinformation Campaigns",
    "Reputational Harm",
    "AI Misinformation",
    "Legal Ethics",
    "Journalistic Integrity",
    "Legal Technology",
    "Child Sexual Abuse Material",
    "Voter Suppression",
    "AI malfunction",
    "Deepfake Nudes",
    "Deepfake Disinformation",
    "Mass Surveillance",
    "Facial Recognition Misidentification",
    "Political Deepfakes",
    "Deepfake Video Manipulation",
    "Manipulated Media",
    "Content Policy Violations",
    "GDPR Privacy Violation",
    "Political Advertising Deception",
    "Deepfake Scams",
    "Health Information Accuracy",
    "Diversity Representation",
    "Voice impersonation",
    "Political Advertisements",
    "Ad Platform Performance",
    "Deepfake Image",
    "Hallucinations",
    "Academic dishonesty",
    "Misleading Legal Citations",
    "Mislabeling",
    "Legal advice",
    "AI-Driven Scams",
    "Algorithmic Staffing Failures",
    "Fraudulent DMCA Notices",
    "Academic Fraud",
    "Ethical Implications",
    "Algorithmic Targeting",
    "Cartel Activities",
    "Autonomous Vehicle Accident",
    "Voice Cloning",
    "Scamming",
    "Cybercrime",
    "Deepfake Technology Misuse",
    "AI reliability",
    "AI Work Assistants",
    "Automotive Safety",
    "Domestic Violence Risk Assessment",
    "Ethics in Journalism",
    "AI limitations",
    "Automated Termination",
    "Market Manipulation",
    "Production Efficiency",
    "Defamation",
    "Game imbalance",
    "Nuclear False Alarm",
    "Image Classification",
    "Ethical AI Use",
    "Ethical Journalism"
]
issues_aiaic = [
    "Accuracy/reliability",
    "Privacy",
    "Safety",
    "Mis/disinformation",
    "Ethics/values",
    "Security",
    "Surveillance",
    "Ethics",
    "Copyright",
    "Employment",
    "Dual/multi-use",
    "Bias/discrimination - race, ethnicity",
    "Human/civil rights",
    "Fairness",
    "Robustness",
    "Bias/discrimination",
    "Effectiveness/value",
    "Appropriateness/need",
    "Bias/discrimination - race",
    "Governance",
    "Cheating/plagiarism",
    "Anthropomorphism",
    "Environment",
    "Business model",
    "Liability",
    "Confidentiality",
    "Freedom of expression - censorship",
    "Fraud",
    "Bias/discrimination - gender",
    "Legal",
    "Competition/price fixing",
    "Employment - jobs",
    "Personality rights",
    "Accountability",
    "Legality",
    "Bias/discrimination - race, ethnicity, gender",
    "Defamation",
    "Bias/discrimination - economic",
    "Necessity/proportionality",
    "Legal - liability",
    "Scope creep/normalisation",
    "Impersonation",
    "Employment - pay",
    "Bias/discrimination - political",
    "Bias/discrimination - disability",
    "Bias/discrimination - race, gender",
    "Legal - defamation/libel",
    "Hypocrisy",
    "Lethal autonomous weapons",
    "Reputational damage",
    "Bias/discrimination - race, ethnicity, income",
    "Freedom of expression",
    "Oversight/review",
    "Bias/discrimination - race, ethnicity, age",
    "Bias/discrimination - nationality",
    "Bias/discrimination - religion",
    "Stereotyping",
    "Employment - pay, jobs",
    "Bias/discrimination - age",
    "Bias/discrimination - profession/job",
    "Bias/discrimination - LGBTQ",
    "Bias/discrimination - race, religion",
    "Competition/collusion",
    "Bias/discrimination - race, income",
    "Historical revisionism",
    "Oversight",
    "Bias/discrimination - language",
    "Identity theft/impersonation",
    "Deepfake - video",
    "Generative adversarial network (GAN)",
    "Neural network",
    "Deep learning",
    "Machine learning",
    "Bias/discrimination - race, gender, age, income",
    "Bias/discrimination - multiple",
    "Employment - jobs, pay",
    "Autonomous lethal weapons",
    "Bias/discrimination - gender, race",
    "Encroachment",
    "Health",
    "Bias/discrimination - race, ethnicity, LGBTQ, transgender",
    "Objectification/dehumanisation",
    "Bias/discrimination - race, ethnicity, income, location",
    "Employment",
    "Dual/muti-use",
    "Mis/disinfomation",
    "Bias/discrimination - race, ethnicity, gender, religion, national identity, location",
    "Bias/discrimination - race, ethnicity, gender, age, disability",
    "Bias/discrimination - location",
    "Copyright, Workforce dislocation/replacement",
    "Personality rights, Workforce dislocation/replacement",
    "Over-reliance",
    "Capacity/resources",
    "Bias/discrimination - race, ethnicity",
    "Accuracy/reliabiity",
    "Reputation",
    "Accessibility, Bias/discrimination - disability",
    "Consumer protection",
    "Sexualisation",
    "Bias/discrimination - racial, gender",
    "Service quality deterioration",
    "GovernancePrivacy",
    "Legality - fraud, marketing",
    "Human/civil rights",
    "Diversity",
    "Ownership/accountability",
    "Financial loss",
    "Lethal Autonomous Weapons",
    "Mis/disinformarion",
    "Incentivisation",
    "Value/effectiveness",
    "Leadership",
    "Mis-representation",
    "Freedom of information",
    "Dual/Multi-use",
    "Governance, Mis/disinformation",
    "Safety - fraud",
    "Bias/disrimination - ethnicity, disability",
    "Bias/discrimination - birthplace",
    "Bias/discrimination - sexual preference (LGBTQ)",
    "Bias/discrimination - gender, race, religion",
    "Employment - pay, working conditions",
    "Employment - safety",
    "Employment - pay/compensation",
    "Accuracy/reliability",
    "Robot rights",
    "Accuracy/reliability, Bias/discrimination, Human/civil rights, Surveillance",
    "Purpose",
    "Values/culture/ethics",
    "Bias/discrimination - income, location",
    "Bias/discrimination - race, ethnicity, gender, age",
    "Corruption/fraud",
    "Reput",
    "Dual-multi-use",
    "Bias/discrimination - income, race",
    "Bias/disrimination - race, ethnicity",
    "Legal - litigation",
    "Accuracy/reliabilty",
    "ethnicity",
    "Bias/discrimination - age, income",
    "Security, Safety",
    "Freedom of expression - right of assembly",
    "Bias/discrimination - race, age, disability",
    "Bias/discrimination - gender, ethnicity",
    "Bias/discrimination - gender, disability, age, location",
    "Bias/discrimination - economic, political",
    "Bias/discrimination - race, ethnicity, education, employment",
    "Bias/discrimination - political opinion",
    "Bias/discrimination - race, ethnicity, disability",
    "Employment - pay, jobs, working conditions, unionisation",
    "Bias/discrimination - age, LGBTQ",
    "Legal - compliance",
    "Ethics/value",
    "Hate speech/violence",
    "Bias/discrimination - politics",
    "IP abuse/misuse",
    "Bias/discrimination - income, geography",
    "Mis/Disinformation",
    "Bias/discrimination - economic, racial",
    "Bias/discrimination - racial, ethnicity",
    "Bias/discrimination - rewilding",
    "Bias/discrimination - gender, race, age, weight",
    "Safety - harassment",
    "Geopolitics",
    "Public health",
    "Dual-/multi-use",
    "Bias/discrimination - race, ethnicity, economy",
    "Harassment",
    "Employment - pay, termination",
    "Monopolisation",
    "Phrenology",
    "Bias/discrimination - age, gender, race, ethnicity",
    "Pseudoscience",
    "Bias/discrimination - income",
    "Bias/discrimination - gender, disability",
    "Accessibility/usability",
    "Bias/discrimination - race, ethnicity, disability, gender",
    "Bias/discimination - race, ethnicity",
    "Legal - Liability",
    "Bias/discrimination - productivity",
]
victim_aiaic=['users', 'Customers', 'consumers', 'children', 'Students', 'Tesla', 'individuals', 'Women', 'Patients', 'privacy', 'journalists', 'Authors', 'Google', 'Public', 'Employees', 'Facebook users', 'voters', 'Uyghurs', 'Black people', 'pedestrians', 'politicians', 'environment', 'Investors', 'Amazon', 'OpenAI', 'researchers', 'artists', 'content creators', 'citizens', 'individual', 'passengers', 'Palestinians', 'Microsoft', 'Teachers', 'Worker', 'University', 'Residents', 'Delivery drivers', 'Drivers', 'Civil rights groups', 'Privacy advocates', 'local residents', 'politician', 'musicians', 'publishers', 'third-party sellers', 'Travellers', 'Voice actors', 'Meta', 'workers', 'passenger', 'employee', 'Taylor Swift', 'Internet users', 'Black community', 'Apple', 'Job applicants', 'Donald Trump', 'Teenagers', 'Motorcyclist', 'Child', 'Facebook', 'Job seekers', 'LGBTQ community', 'Social media platforms', 'asylum seekers', 'cybersecurity professionals', 'communities of colour', 'news anchor', 'immigrants', 'low-income litigants', 'journalist', 'copyright holders', 'minors', 'US citizens', 'families with disabilities', 'families', 'designers', 'celebrities', 'Reddit users', 'Instagram users', 'Advertisers', 'Scarlett Johansson', 'Writers', 'Weapons detection company', 'President', 'scientific community', 'Worldcoin', 'Student', 'Adobe', 'African Americans', 'job candidates', 'lawyer', 'police', 'school children', 'pedestrian', 'welfare beneficiaries', 'Actor', 'The Guardian', 'News publishers', 'ChatGPT', 'Disney', 'People', 'Social media users', 'Girls', 'Inmates', 'Snapchat users', 'Uber drivers', 'People of color', 'businessman', 'Protestors', 'Content moderators', 'Photographer', 'Twitter users', 'Driver', 'Jewish community', 'Black girls', 'Black individuals', 'Firefighters', 'OkCupid users', 'Mental health non-profit', 'Tesla owners', 'Society', 'Critics', 'Public Health', 'Ocado', 'TikTok users', 'Gig workers', 'technology company', 'couriers', 'ride-sharing passengers', 'online users', 'warehouse employees', "survivors and victims' families", 'public figures', 'parents', 'humanity', 'young people', 'migrant children', 'BAME individuals', 'individuals on the Gangs Violence Matrix', 'ride-hailing customers', 'recruiters', 'general users', 'police departments', 'law enforcement', 'delivery robot', 'wheelchair users', 'car driver', 'car owners', 'grieving families', 'companies', 'smaller, community-based cultural organisations', 'visa applicants', 'defendants', 'women and children', 'intellectual property holders', 'people from Albania, Greece, Romania, and Bulgaria', 'website publishers', 'doctors', 'election officials', 'news consumers', 'French residents', 'vulnerable populations', 'game developers', 'HR professionals', 'music industry', 'sellers', 'benefit claimants', 'robot', 'advertising executives', 'website operators', 'historians', 'geoscientists', 'Photo owners', 'Photograph Owners', 'Indian model', 'YouTube users', 'Students and staff', 'College student', 'Dataset', 'Individuals with darker skin tones', 'Emily Bender', 'Criminal Justice System', 'Web users', 'Charity', 'Marketing team', 'Dave Fanning', 'US lawmakers', 'Shaun Thompson', 'Female veterans', 'Ansel Adams estate', 'Palestinian people', 'Innocent Shopper', 'Eventbrite', 'Bungie', 'Female celebrities', 'Voiceover actors', 'Sony Music Group', 'Newspapers', 'Security industry', 'Software developers', 'Philippines government', 'The Authors Guild', 'CEO', 'Football fan', 'Thai woman', 'Former Employee', 'AI companies', 'BBC presenter', 'John Swinney', 'UK police', 'Honda driver', 'Chanel', 'financial markets', 'Aerospace Professor', 'NBA star', 'Clergy', 'artist', 'Principal', "Tupac Shakur's estate", 'underage users', 'motorists', 'viewers', 'World Health Organisation', 'Influencer', 'Danish publisher', 'film studio', 'Educators', 'European Parliament', 'Greek Ministry', 'ethics', 'Euronews', 'train company', 'screenwriter', 'voiceover artist', 'suspected militants', 'plaintiff', 'homeless', 'Anies Baswedan', 'Mayor', 'Dean Phillips', 'DiDi', 'New Yorkers', 'actress', 'BBC', 'Chicago police', 'Godfrey Gao and Coco Lee', 'Ukrainian officials', 'filmmakers', 'LEGO', 'Georgia Meloni', 'advertiser', 'Edgenuity', 'online proctoring company', 'UK citizens', 'Applicants', 'Bulgarian nationals', 'Princess', "Italy's Interior Ministry", 'Municipality', 'Native Americans', 'female reporter', 'AI engineer', 'election integrity', 'City Council', 'taxpayers', 'US Presidential candidate', 'Minority communities', 'Defendant', 'journalism', 'prisoners', 'websites', 'Indian Government', 'crypto exchanges', 'recipients', 'renters', 'cybersecurity', 'customer', 'Voice Actor', 'voiceover artists', 'cyclist', 'Buckingham Palace', 'court', 'Knightscope', 'tourists', 'couple', 'First Republic Bank', 'professional athletes', 'members of Congress', "George Carlin's estate", 'Texas man', 'Pokemon', 'company', 'porn stars', 'human influencers', 'gamer', 'Wizards of the Coast', 'Claimants', 'Chevrolet dealership', 'Bruce Willis', 'Young woman', 'Financial news sites', 'Local Police', 'Pediatricians', 'Michael Cohen', 'Screenwriters', 'young girl', 'Keith Haring', 'Hostages and injured civilians', 'Singapore Prime Minister', 'Omegaverse authors', 'Academic Researchers', 'Content supporting Palestine', 'Afghan refugee', 'The New York Times', 'Media professionals', 'Medical Professionals', 'Attendees', 'shoppers', 'Elderly people', 'United States', 'University student', 'AP reporter', 'Political candidates', 'Illinois residents', 'Bavarian citizens', 'Palestinian civilians', 'Steven Michael Hendrickson', 'Rapper', 'OpenAI and Microsoft', 'Sports Magazine', 'Judge', 'Fictitious financial investment company', 'TikTok', 'Immunefi', 'Mark Walters', 'Samsung', 'Privacy advocate', 'Stability AI & OpenAI', 'Australian Research Council (ARC)', 'Chatbots', 'Gannett', 'Polish users', 'Israeli Prime Minister', 'Software Engineers', 'Palestinian', 'Orphans', 'International Olympic Committee (IOC)', 'Replika', 'Pashto-speaking Afghan refugee', 'elections', 'Palestinian children', 'Deloitte and KPMG', 'Canadian residents', 'US President Joe Biden', 'Greta Thunberg', 'Bella Hadid', 'Developers', 'Barack Obama', 'Former leader', 'Lead Defense Lawyer', '13-year-old girl', 'Proctorio', 'Innocent individuals', 'Sir Keir Starmer', 'Music publishers', 'Black students', 'Miami University student', 'AI image detector', 'Protesters', 'Progressive Slovakia', 'Gamers', 'Snap Inc', 'YouTube star', 'buyers', 'Washington Post journalists', 'Beneficiaries', 'rival retailers', 'fans', 'Car drivers', 'Buzzfeed', 'Chinese artists', 'Getty Images', 'Quora', 'Black homeowners', 'Amazon employees', 'banks', 'Minority populations', 'Anil Kapoor', 'Food bank', 'driver and baby', 'Bakery owner', 'Jean Louis', 'Transgender drivers', 'Clients', 'Amazon customer', 'Deceased NBA player', 'US military', 'Fathers', 'Chess players', "Victims' families", 'Danish biologist', 'France', 'Jews, women, Muslims', 'Wanda Holbrook', 'rape victims', 'Convicted sex offender', 'TV presenter', 'Human rights lawyer', 'Professor and his wife', 'Babysitters', 'Walmart workers', 'civil society', 'Brave', 'Portland Metro', 'human priests', 'religious clergy', 'humans', 'Verkada customers', 'Riders', 'Postmates riders', 'Cruise', 'Interpreters', 'Robert McDaniel', 'Kyle Behm', "Elis Regina's legacy", 'Knight Capital Group', 'Teacher', 'Nest', 'Patient', "Pak'nSave", 'Minority Groups', 'Author', 'Maria Schaake', 'Porcha Rudruff', 'Dr. Janice Duffy', 'Richard Lee', 'Invento Robotics', 'Pope Francis', 'UK Prime Minister Rishi Sunak', 'Joe Biden', 'MIT student', 'Delphi', 'tenants', 'PS Radhakrishnan', 'Non-native English speakers', 'Gizmodo', 'None', 'City', 'Martin Lewis', 'Participants', 'broadcast TV job', 'Queen Elizabeth II', 'CNN', 'Jay-Z', 'Twitter', 'Hunter Biden', 'Datuk Seri Ismail Sabri Yaako', 'Belgian Prime Minister', 'The late Queen Elizabeth II', 'film artists', 'Discord', 'Luke Ashton', 'policeman', 'Bernard A. Jones', 'emergency responders', 'Dr. Anthony Fauci', 'Russian president Valdimir Putin', 'Frank Ocean', 'JustEat drivers', 'NEDA employees', 'Professor', 'Singer', 'Legal advisor', 'US stock market', 'USPS', 'Chicago retiree', 'Kurdish businessman and Turkish investigative journalist', 'Presidential candidate', 'Irish Times', 'Organiser', 'news organizations', 'Elderly couple', 'Mother', 'Amnesty', 'Human models', 'Photography industry', 'Michael Schumacher', 'Universal Music Publishing Group', 'Motorcyclists', 'ChatGPT users', 'Pope', 'Kevin Roose', 'Wikipedia', 'Bodega/Corner store owners', 'Ethicists', 'San Francisco Municipal Transit Authority', 'Belgian man', 'Brian Hood', 'Jonathan Turley', 'Reddit community', 'Open AI', 'Driver of the Tesla', "Javier Maldonado's family", 'Arvind Kejriwal', 'Naibel Benevides Leon', 'UK energy company', 'Buddhism', 'Kiwibot', 'Dong Mingzhu', 'Henn-na Hotel', 'Chevrolet Bolt EV test car', 'Uber', 'Female CEOs', 'Communities', 'Female users', 'Black teenagers', 'shooting suspect', 'Man', 'Dr. Albert Yeung', 'French civil rights group', 'surgeon', 'Bettina Wulff', 'Japanese man', 'Milorad Trkulja', 'Fabio (robot)', 'Visitors', 'Neighbours', 'Contractor', 'Actresses', 'Mohamed Azmin Ali', "Gabon's President", 'Players', 'Scottish offenders', 'Apple engineer', 'Joshua Brown', "Gao Yaning's family", 'Paul Zilly', 'Hollywood stars', 'Joe Rogan', 'elderly', 'Mohammed Khadeer', 'occupants', 'teenager and motorcyclist', 'Alexey Tretyakov and his children', 'facial recognition technology', 'Gilberto Alcazar Lopez and Maria Guadalupe Nieves-Lopez', 'models', 'Steve Talley', 'Michael Oliver', 'Nijeer Parks', 'Robert Williams', 'African American inmates', 'Eric Loomis', 'Alonzo Sawyer', 'Villagers', "Nash County Sheriff's Office", 'Woman', 'Female gamers/content creators', 'civil rights advocates', 'German geocoding company', 'Creative Communities', 'Illustrator', 'bystanders and uninvolved people', 'Hangzhou city government', 'Controversial psychologist', 'German civil rights NGO', 'Yandex', 'Chinese technology company', 'Nothing, Forever team', 'TV anchors', 'Arts organizations', 'Animators', 'Professor and Tigrayan ethnic group member victimized by murder and defamation on Facebook.', 'Historical Figures', 'Professors', 'Manga artist', 'Ring users', 'News journalists', 'Graphic designers', 'iRobot', 'Ski resort emergency dispatch centres', 'Georgia man', 'Airline staff', 'Binance', 'Cryptocurrency investors', 'Black singers', 'Swim Drink Fish', 'Black borrowers', 'Healthcare Industry', 'Jobseekers', 'private jet', 'Competitors', 'US human rights campaigners', 'High-profile women', 'San Francisco Police Department', 'Lockport City School District', 'Lawyers', 'LinkedIn', 'Tesla employee', 'Russian soldiers', 'Peace organization', 'Make-up artists', 'Ukraine president', 'Russian bot farms', 'restaurant owner', 'Instacart', 'Civilians', 'Human rights organizations', 'Ukrainian authorities', 'Accounts sharing intelligence', 'Foreign students', 'Disabled People', "Suicide victims' families", 'Homeless people', 'Florida lawmaker', 'UAE', 'Text-to-speech service', 'National Highway Traffic Safety Administration', 'Data protection authority', 'Muslim women', 'The DAO investors', 'MoviePass users', 'Social activists', 'Taxi driver', 'Freedom of expression', 'Pony.ai', 'Beta tester', 'Political entities', 'Waitstaff', 'Foreign journalists', 'Zillow Group', 'Web accessibility experts', 'Blind individuals', 'Religious institutions', 'Religious conservatives', 'Mobile users', 'Left-wing entities', 'Harvard students', 'Delivery riders', 'Shirt brand', 'Primary school pupils', 'Primary School', 'Dr. Mary Fairhurst', 'State Taxation Administration', 'Indigenous peoples', 'Software engineer', 'Public school teachers', 'Police Officers', 'Ethnicity', 'Xiaomi', 'Privacy campaigners', 'Opposition', "Head of Iran's nuclear programme", "Women's Health Advocates", 'Uyghurs, Tibetans, Koreans', 'Civil Liberties', 'Nio', 'Japanese visually impaired athlete', 'Voice artists', 'Nurses', 'Minority Applicants', 'Minority borrowers', 'Unity employees', 'Racial justice protestors', 'US adults', 'Black former NFL players', 'Conservationists', 'Military', 'Biostatisticians', 'Hotel chain', 'SoftBank', 'Film industry', 'Black teenager', 'Minorities', 'Game publishers', 'Emergency Nurses', 'small businesses', 'Black creators', 'Video game actor', 'Flex drivers', 'K-pop artists', 'Bytedance', 'Canadians', 'Physicians', 'Human rights', 'Teenager', "Cambodian victims' families", 'Digital Media Strategists', 'Black hosts', 'Palestinian social media users', 'Global Public Opinion', 'Latitude', 'Immigration officers', 'Civil rights organizations', 'Real estate companies', 'People with disabilities', 'Lawmakers', 'Satellite imagery industry', 'Vulnerable people', 'Truck driver', 'Family', 'State troopers', 'University faculty', 'College students', 'Social Scientists', 'Teenage cheerleaders', 'US Customs and Border Protection (CBP)', 'Town', 'Former chief minister', 'Amazon Ring users', 'Rights activists', 'Passenger and Driver', 'LGBTQ+ community', 'Celebrity', 'Bathroom fixture maker, Fashion house, Car manufacturer', 'Non-profit organization', 'Belgian government', 'Muslims', 'Medicaid users', 'Bitcoin investors', 'Deliveroo riders']
victim_incidents= \
    ['Facebook users', 'Tesla drivers', 'Women', 'Minority Groups', 'General public', 'unknown', 'Microsoft',
     'Motorists', 'Black people', 'Women', 'Minority Groups', 'internet users', 'Uber drivers', 'ChatGPT users',
     'minors', 'Children', 'patients', 'Twitter Users', 'Accused People', 'Amazon Customers', 'email users',
     'pedestrians', 'Amazon users', 'Facebook users having posts about painful events', 'Facebook users',
     'Jewish people', 'Bing users', 'San Francisco firefighters', 'San Francisco Fire Department', 'TikTok users',
     'public figures', 'celebrities', 'Google users', 'Navya', 'Keolis North America', 'bus passengers',
     'Elaine Herzberg', 'pedestrians', 'Starbucks employees', 'Robotics Consultant', 'Airplane Passengers',
     'Airplane Crew', 'pedestrians', 'Motorists', 'Gmail Users', 'Wikimedia Foundation', 'Wikipedia Editors',
     'Wikipedia Users', 'People with Twins', 'Asian People', 'Apple', 'Device Owners', 'Oliver Haberstroh', 'Neighbors',
     'Fire Victims', 'Dong Mingzhu', 'Medical Residents', 'Yandex Users', 'Individual Kaggle Competitors',
     'drivers in Jokkmokk', 'drivers in Sweden', 'Volvo', 'Carollers', 'Child', 'Ramji Lal', 'People with Dark Skin',
     'Store Patrons', 'Oakland Residents', 'Knightscope', 'Joshua Brown', 'Alex Harker', 'my_handy_design',
     'Australian welfare recipients', 'OpenAI', 'DAO Token Holders', 'Mountain View municipal bus passengers',
     'Mountain View municipal bus', 'Chinese Communist Party', 'Tencent Holdings', 'Microsoft', 'Turing Robot',
     'unnamed Palestinian Facebook user', 'Palestinian Facebook users', 'Arabic-speaking Facebook users',
     'Facebook users', 'Facebook users', 'Facebook users interested in COVID information',
     'Facebook users interested in the US Presidential Election', 'International Baccalaureate students',
     'Jewish people', 'Google Images users', 'non-white neighborhoods', 'communities of color', 'Jewish people',
     'Jewish public figures', 'patients of minority groups', 'low-income patients', 'female patients',
     'Hispanic patients', 'patients with Medicaid insurance', 'Leaving Certificate exam takers',
     'Irish Department of Education and Skills', 'Robert Julian-Borchak Williams', 'Black people in Detroit',
     'job applicants using HireVue', 'HireVue customers', 'New York City low-income communities',
     'Stanford Medical frontline workers', 'Stanford Medical residents', 'Buenos Aires children', 'YouTube users',
     'Facebook users', 'Facebook users interested in the Lekki Massacre incident', 'Facebook users of minority groups',
     'non-American-born Facebook users', 'non-Christian Facebook users', 'Facebook users interested in accessibility',
     'Facebook users interested in Hispanic culture', 'Cogo Guebara', 'unnamed woman injured in the fight',
     'Houston Independent School District teachers', 'livestream viewers', 'Black patients',
     'African-American patients', 'dark-skinned people', 'dark-skinned women', 'Apple Card female users',
     'Apple Card female credit applicants', 'Deliveroo workers with legitimate reasons for cancelling shifts',
     'Deliveroo workers', 'Amazon Flex employees', 'Amazon Flex drivers', 'California low-income neighborhoods',
     'California communities of color', 'Korean Facebook Messenger users', 'Korean people of gender minorities',
     'Korean people with disabilities', 'Genderify customers', 'gender minority groups', 'Jovani Maldonado',
     'Benjamin Maldonado', 'California public', 'Dutch Tax Authority', 'Dutch families', 'Twitter Users',
     'Twitter non-white users', 'Twitter non-male users', 'Troy residents', 'Troy Police Department',
     'Syracuse residents', 'Syracuse Police Department', 'San Francisco residents', 'San Francisco Police Department',
     'San Antonio residents', 'San Antonio Police Department', 'New York City residents',
     'New York City Police Department', 'Fall River residents', 'Fall River Police Department', 'Chicago Residents',
     'Chicago Police Department', 'Lucie Inland', 'Amazon delivery drivers', 'Amazon workers', 'Reddit users',
     'Arkansas Medicaid waiver program beneficiaries', 'Arkansas healthcare workers', 'Lamya Robinson',
     'Black Livonia residents', 'Rekognition users', 'arrested people', 'Uyghur people', 'Xsolla employees',
     'Black college students', 'Latinx college students', 'indigenous students', 'Libyan soldiers', 'Black people',
     'Facebook users', 'Muslims', 'University of Toronto BIPOC students', 'Moshe Har Shemesh',
     'Israeli people having tax fines', 'internet users with disabilities', "web accessibility vendors' customers",
     'Facebook users', 'Facebook content creators', 'California bar exam takers', 'flagged California bar exam takers',
     'Gilberto Alcazar Lopez', 'Maria Guadalupe Nieves-Lopez', 'Amazon fulfillment center workers',
     'University of Illinois students of color', 'University of Illinois students', 'TikTok users',
     'TikTok users under 18 years old', 'TikTok users', 'TikTok content creators', 'Antonio Radic',
     'YouTube chess content creators', 'YouTube users', "Kristin Livdahl's daughter", 'Amazon Echo customers',
     'children using Alexa', 'SoftBank', 'female Facebook users', 'Black Facebook users', 'male Facebook users',
     'Facebook users', 'LinkedIn users', 'YouTube users', 'Twitter Users', 'Netflix users',
     'TikTok content creators of marginalized groups', 'Sennett Devermont', 'Beverly Hills citizens',
     'Fuzhou Zhongfang Marlboro Mall goers', 'news sites',
     'University of Texas at Austin PhD applicants of marginalized groups',
     'Google Maps users traveling in Sierra Nevada', 'Google Maps users traveling in the mountains', 'Paula Knight',
     'Bath officials', 'UK public', 'San Francisco city government', 'sepsis patients', 'people attempting suicides',
     'Facebook users of small language groups', 'Twitter users of small language groups', 'Amazon workers',
     'Amazon delivery drivers', 'Target customers', 'Facebook users of disabilities', 'adaptive fashion retailers',
     'Hong Kong bank manager', 'inmates of color', 'people having non-Caucasian facial features', 'Zillow Offers staff',
     'Zillow', 'Black patients', 'LGBTQ people', 'LGBTQ people of color', 'non-American LGBTQ people', 'Jade Thirlwall',
     'Leigh-Anne Pinnock', 'Facebook users of minority groups', 'Facebook users', 'UK ETS past test takers',
     'UK ETS test takers', 'UK Home Office', 'Natural Cycles users', 'Women', 'Rohingya people',
     'Rohingya Facebook users', 'Myanmar public', 'Facebook users in Myanmar', 'Burmese-speaking Facebook users',
     'Ocado', 'Eric Horvitz', 'Tesla drivers', 'Amaya Ross', 'Black students', 'Black test-takers',
     'Oregon State University', 'freight train crew', 'São Paulo Metro users', 'São Paulo citizens', 'Pasco residents',
     'Pasco Black students', 'Pasco students with disabilities', 'LinkedIn users', 'Malaysian convicted people',
     'unnamed Australian telecommunications company', 'Tinder users over 30 years old', 'Korean public',
     'Black WeChat users', 'Cruise vehicle', 'trans women', 'women of color', 'Cruise vehicles',
     'Cruise driver employee', 'Doctors', 'COVID patients', 'Volodymyr Zelenskyy', 'Ukrainian social media users',
     'Ukrainian public', 'San Francisco public', 'Cruise customers', 'Tesla owner', 'Vision Jet owner', 'sex workers',
     'Airbnb users', 'small businesses on Facebook', "unnamed UK-based energy firm's CEO",
     'Spanish victims of gender violence', 'road engineer', 'underrepresented groups', 'Minority Groups',
     'American physicians', 'American pharmacists', 'American patients of minority groups', 'American patients',
     'Google Docs users', 'Shophie Wilmès', 'Belgian government', 'Zhihu employees', 'Chinese tech workers',
     'Black students', 'fair visitors', 'Target', 'Target customers', 'TikTok users', 'TikTok new users',
     'delivery truck', 'pedestrians', 'Tesla drivers', 'Ever AI users', 'Instagram users', 'Snapchat users',
     'American social media users', 'Salta teenage girls', 'Salta girls of minority groups', 'Naver customers',
     'rhinos in conservation', 'people with disabilities', 'Facebook content moderators',
     "pseudonymous Estée Lauder's former staff", 'XPeng Motors customers', 'Pakistani citizens',
     'Honolulu homeless people', 'John Bernal', 'San Jose public', 'Ukrainian social media users', 'Ping An customers',
     'Chinese minority groups', 'Thoughts users', 'Twitter Users', 'Hive Box customers', 'WeChat Pay users', 'students',
     'low-income minority students', 'Teachers', 'oncologists', 'cancer patients', 'Yoshihiro Umeda', 'pedestrians',
     'Tesla drivers', 'Umesh Ramesh Dhake', 'Jeremy Beren Banner', 'Tesla users', 'Mark Molner', 'Gao Yaning',
     'Tesla drivers', 'Brian Hofer', 'Intellectual Property rights holders', 'Indian voters',
     'Indian social media users', 'Indian women journalists', 'tourists', 'Waze users', 'YouTube users',
     'YouTube content creators', 'the Gilliam family', 'Tumblr content creators', 'Tumblr users', 'tourists',
     'Apple Maps users', 'Denise Green', 'Los Gatos residents', 'children of minority groups',
     'families of minority groups', 'Sherman Oaks residents', 'Waze users', 'Los Angeles city government',
     'child named Christopher', 'Twitter', 'Twitter Users', 'Twitter users participating in COVID-19 discussions',
     'Landon Embry', 'motorcyclists', 'Tesla drivers', 'small businesses on Amazon', 'Amazon Customers',
     'FaceApp non-binary presenting users', 'FaceApp transgender users', 'FaceApp users',
     'internet social platform users', 'Chicago drivers', 'unnamed property owner', 'The Good Guys customers',
     'Kmart customers', 'Bunnings customers', 'UK drivers', 'non-TPI-registered Grab drivers',
     'Grab drivers in Indonesia', 'Grab drivers', 'US naturalized citizens', 'US immigrants',
     'US citizenship applicants', 'US immigration applicants', 'San Francisco homeless people', 'Renren',
     'Buding Movie Tickets', 'Yi Xia', 'Dangdang', 'Chinese startups', 'Chinese companies',
     'victims of crimes documented on social media', 'investigative journalists',
     'International Criminal Court investigators', 'International Court of Justice investigators',
     'criminal investigators', 'Michael Williams', 'Replika users', 'Replika male users', 'Replika',
     'San Francisco traffic participants', 'San Francisco public', 'Uyghur people', 'Turkic Muslim ethnic groups',
     'Google Photos users residing in Illinois', 'Google Photos users', 'Illinois residents',
     'Virginia convicted felons', 'Virginia Black offenders', 'Virginia young offenders', 'social media users',
     'Instagram users', 'Facebook users', 'neighborhoods of color', 'Brown communities', 'Black communities',
     'Adam Toledo', 'US schools', 'US students', 'Minority Groups', 'underrepresented groups',
     'YouTube young male users', 'YouTube male users', 'Caleb Cain', 'Pa Edrissa Manjang',
     'Uber Eats Black delivery drivers', 'Jewish people', 'BlenderBot 3 users',
     'Facebook users sharing photo evidence of slavery', 'Facebook users', 'Google Lens users', 'Cruise passengers',
     'Toyota Prius passengers', 'Olivia Solon', "Olivia Solon's Facebook connections", 'You You Xue', 'Tesla drivers',
     'Nabla customers', 'Ousmane Bah', 'NYC Black people', 'NYC Black young people', 'Tesla drivers',
     'Culver City Fire Department', 'UK visa applicants from some countries', 'Silicon Valley traffic participants',
     'Silicon Valley residents', 'TikTok male teenager users', 'TikTok male users', 'TikTok teenage users',
     'TikTok users', 'TikTok', 'Derrick Monet', 'Jenna Monet', "the Monets' family", 'Black women', 'Black people',
     'Google users', 'Japanese pornographic actors', 'Laguna Beach Police Department', 'Facebook users',
     'Twitter Users', 'YouTube users', 'Waymo passengers', 'police investigators',
     'California Department of Motor Vehicles', 'Tesla customers', 'California residents',
     'Coffee Meets Bagel users having no ethnicity preference', 'Coffee Meets Bagel users',
     'local law enforcement officers', 'YouTube users', 'YouTube climate-skeptic users', 'unnamed Tesla driver',
     'Tesla drivers', 'Henn na Hotel guests', 'Henn na Hotal staff', 'The Vindicator',
     'job candidates using MyInterview', 'job candidates using Curious Thing', 'employers using MyInterview',
     'employers using Curious Thing', 'YouTube users skeptical of US election results', '15.ai', '15.ai users',
     'Honda customers', 'Nissan drivers', 'traffic participants', 'unnamed woman passenger',
     'The Seed Company by E.W. Gaze', 'businesses on Facebook', 'Bucheon citizens', 'Sunnyside beachgoers',
     'Marie Curtis beachgoers', 'Toronto citizens', 'Twitter left-leaning politicians',
     'Twitter left-leaning news organizations', 'Twitter left-leaning users', 'Twitter Users', 'Marietje Schaake',
     'unnamed 22-year-old male driver', 'Tesla drivers', 'Instagram users', 'William Varner', 'unnamed passenger',
     'Lalani Erika Renee Walton', 'Arriani Jaileen Arroyo', "Lalani Erika Renee Walton's family",
     "Arriani Jaileen Arroyo's family", 'TikTok young users', 'TikTok users', 'iPhone Face ID users',
     'iPhone X Face ID users', 'Notting Hill Carnival goers', 'students at Charlotte Mecklenburg Schools',
     'teachers at Charlotte Mecklenburg Schools', 'security officers at Charlotte Mecklenburg Schools',
     'Women of Sex Tech conference attendants', 'Women of Sex Tech conference organizers',
     'Facebook users posting legitimate COVID-19 news', 'Facebook users', 'Instagram users', 'Facebook users',
     'a software engineer named Mark', 'parents using telemedicine services', 'Teachers', 'non-cheating students',
     'cheating students', 'Marcus Rashford', 'Jadon Sancho', 'Bukayo Saka', 'Facebook users', 'Instagram users',
     'Twitter Users', 'Sirey Zhang', "Geisel School of Medicine's students", "Geisel School of Medicine's professors",
     "Geisel School of Medicine's accused students", 'FInals attendees', 'falsely accused Finals attendees',
     "Walter Huang's family", 'Walter Huang', 'museums on Facebook', 'Facebook users interested in arts',
     'Facebook users', 'TheFaceTag app users', 'TikTok young users', 'TikTok users',
     'call center agents having non-Midwestern-American accent', 'people having non-Midwestern-American accent',
     'unnamed Tesla owner', 'Tesla drivers', 'Stability AI', 'deepfaked celebrities', 'Connecticut State Police',
     'none', 'Russian pornographic actresses', 'Russian sex workers', 'YouTube young users', 'YouTube users',
     'Nijeer Parks', 'Jisuk Mok', 'Frisco residents', 'vehicle repair shops', 'vehicle owners',
     'unnamed Florida teenager', 'UK immigrant newlyweds', 'Halle Bailey', 'Black actresses',
     'historically disadvantaged groups', "Google's competitor shopping services", 'TuSimple', 'State of Arizona',
     'Facebook users posting about Plymouth Hoe', 'Facebook users in Plymouth Hoe', 'Plymouth Hoe residents',
     'women in need of abortion services', 'women having unexpected or crisis pregnancies',
     'unemployed Michigan residents falsely accused of fraud', 'unemployed Michigan residents', 'apartment renters',
     "Danielle's family", 'Amazon Echo users', 'Weibo', 'Chinese government', 'Jeremy Banner', "Jeremy Banner's family",
     'Black Google Home Mini users', 'Google Home Mini users', 'Sebastian Galassi', "Sebastian Galassi's family",
     'transgender Uber drivers', 'Stephan de Vries', 'Filipinos', 'the Karnataka government', 'Kannada speakers',
     'poor neighborhoods', 'neighborhoods of color', 'students', 'Rock Hill School students',
     'Pinecrest Academy Horizon students', 'Transgender YouTubers', 'transgender people',
     'young men having credit scores', 'people scored on old scoring versions', 'people changing addresses frequently',
     'political organizations', 'political candidates', 'Twitter Users', 'Twitter',
     'Finland National Bureau of Investigation', 'Xi Jinping', 'Aung San Suu Kyi', 'Real Women in Trucking',
     'older female blue-collar workers', 'low digitally skilled Facebook users', 'Uber drivers in India',
     'digital artists', 'artists publishing on social media', 'artists', "victims of FTX's collapse", 'Twitter Users',
     'women using Lensa AI', 'Asian women using Lensa AI', 'Canadian students', 'XPeng driver', 'traffic participants',
     'emergency vehicles', 'Cruise passengers', 'Cruise', 'HSBC UK customers', 'Dan Simmons', 'Silvon Simmons',
     'Kelly Conlon', 'Alexis Majano', 'Airline Passengers', 'low-income communities', 'communities of color',
     'Black Chicago residents', 'traffic participants', 'Tesla drivers', 'Coupang suppliers', 'Coupang customers',
     'traffic participants', 'small businesses in India', 'Amazon customers in India', 'Michael Oliver',
     'Black people in Detroit', 'travelers in Korean airports', 'US Air Force', 'UK Royal Air Force', 'Kevin Main',
     'David Williams', 'mass shooting victims', 'Durham residents', 'Durham Police Department', 'Twitch users', 'Vedal',
     'research participants', 'Koko customers', 'Kenyan Sama AI employees', 'Getty Images', 'Getty Images contributors',
     'Replika users', 'plagiarized entities', 'CNET readers', 'San Francisco residents', 'San Francisco firefighters',
     'San Francisco Fire Department', 'Apple Watch users doing winter activities', 'ski patrols',
     'emergency dispatchers', 'people having medical photos online', 'LinkedIn users', 'Instagram users',
     'Facebook users', 'OpenAI', 'Microsoft', 'racial minorities', "McDonald's customers", 'Walmart employees',
     'gender minority groups', 'racial minority groups', 'underrepresented groups in training data',
     'Palestinians residing in the West Bank', 'Souther Co-op customers', 'political opposition in Uganda',
     'Facebook users speaking Swahili', 'Facebook users speaking English', 'Facebook users',
     'Chinook Centre mall goers', 'Market Mall goers', 'artists submitting in the digital arts category',
     'digital artists', 'artists', 'Amazon delivery drivers', 'SIT Acronis Autonomous', 'A-level pupils', 'GCSE pupils',
     'pupils in state schools', 'underprivileged pupils', 'OpenAI',
     "people having personal data in GPT-2's training data", 'Black residents in Edmonton', 'Black people in Brazil',
     'Black people in Bahia', 'interviewers of remote-work positions', 'employers of remote-work positions',
     'YouTube content creators', 'Twitch content creators', 'TikTok content creators', 'Instagram content creators',
     'WNY Gardeners', 'gardening Facebook groups', 'Facebook users in gardening groups',
     'Palestinian social media users', 'Facebook users', 'Instagram users', 'Twitter Users',
     'Facebook employees having families affected by the conflict', 'Google Pixel 6a users', 'Thai citizens',
     'elder Thai citizens', 'Molly Rose Russell', 'the Russell family', 'teenage girls', 'teenagers',
     'Amazon warehouse workers', 'young TikTok users', 'TikTok users', 'Gen Z TikTok users', 'Tesla drivers',
     'horse-drawn carriages', 'Minority Groups', 'Meta AI', 'Meta', 'Facebook', 'Minority Groups', 'Latitude',
     'Shannon Carpenter', "McDonald's customers residing in Illinois", "McDonald's customers",
     'Facebook users speaking East African languages', 'Facebook users in East Africa',
     "pseudonymized psychiatrist's patients", 'pseudonymized psychiatrist', 'patients', 'healthcare providers',
     'sex workers using Facebook', 'Stack Overflow users', 'Stack Overflow', 'live-stream ceremony viewers',
     'King Maha Vajiralongkorn', 'ChatGPT users', 'OpenAI', 'Black State Farm customers', 'gay men in New York City',
     'Julio Ramirez', 'foreign journalists in Henan', 'international students in Henan', 'Black people in Louisiana',
     'Randall Reid', 'US Navy', "Nathan White's family", 'Nathan White', 'Spanish-speaking Instagram users', 'Immunefi',
     'CNET readers', 'Frauke Zeller', 'David Harris', 'Black taxpayers', 'Twitch users', 'transgender communities',
     'LGBTQ communities', 'Teachers', 'students', 'Google', 'Google shareholders', 'Tigrinya-speaking Facebook users',
     'Facebook users in Ethiopia', 'Ethiopian public', 'Afaan Oromo-speaking Facebook users', 'Replika users',
     'Replika', 'victims in Paris attacks', 'Nohemi Gonzalez family', 'Nohemi Gonzalez', 'Tesla drivers',
     'city traffic participants', 'Tesla', 'Maya Higa', 'female streamers', 'female content creators', '@Sweet Anita',
     '@QTCinderella', '@Pokimane', 'Vanderbilt University students', 'Vanderbilt University', 'Mohammed Khadeer',
     'Haitian asylum seekers', 'African asylum seekers', 'Black asylum seekers', 'Lloyds Bank', 'Venezuelan people',
     'social media users', 'Clarkesworld', "Ben Perkin's parents", 'Perkins family', 'unnamed female college student',
     'Twitter Users', 'social media users', 'Black families in Allegheny',
     'households with disabled people in Allegheny', 'Hackneys family', 'Family and Friends of Deceased', 'Belgian Man',
     'Jonathan Turley', 'Brian Hood', 'Pope Francis', 'Italian children', 'Italian minors', 'Starship Technologies',
     'political campaigns', 'Facebook users', 'Centrelink account holders', 'Your CBD Store',
     'University of Pittsburgh Police Department', 'Phillipsburg High School', 'Hempstead High School',
     'Dubuque Police Department', 'Bellefonte Area High School', 'Justine Hsu', 'Universal Music Group', 'The Weeknd',
     'Drake', 'Uber drivers', 'gig workers', 'Amazon delivery workers', 'Amazon', 'racial minority groups', 'Women',
     'gender minority groups', "Facebook's children users", "Instagram's children users", 'Jennifer DeStefano',
     'DeStefanos family', 'Texas A&M University students', 'Twitter Users', 'Stock Holders',
     'Family of People Near Pentagon', 'Kemal Kilicdaroglu', 'Muharrem İnce', 'Ronald L. Haeberle', 'Ron Haviv',
     'Raymond D’Addario', 'Lynsey Addario', 'Lee Miller', 'Larry Towell', 'James Nachtwey', 'Tillman Mitchell',
     'the Mitchells family', 'Paul Tremblay', 'Mona Awad', 'authors of copyrighted works', 'Alexa children users',
     'research grant administrators', 'research grant applicants', 'internet users', 'Children', 'social media users',
     'Clive Kabatznik', 'Bank of America', 'Hawaiian government', 'General public', 'American government',
     'Barack Obama', 'Oprah Winfrey', 'Jamie Foxx', 'Joan Rivers', 'Phil McGraw', 'Yahoo! News', 'E! News', 'TikTok',
     'General public', 'Queen Elizabeth II', 'British Royal Family', "British Royal Family's staff",
     'Jaswant Singh Chail', 'General public', 'Facebook Messenger users', 'Microsoft', 'Microsoft employees',
     'Third parties relying on the confidentiality of the exposed data', 'Slovakian electorate', 'Monika Todova',
     'Michal Šimečka', 'Democratic process in Slovakia', 'Gizmodo journalists', 'Non-cisgender individuals',
     'LGBTQ+ community',
     'Black men who underwent lung function tests between 2010 and 2020 and potentially received inaccurate or delayed diagnoses and medical interventions due to the biased algorithm',
     'Children', 'General public', 'minors', 'teenagers', 'Children whose data was collected and used for advertising',
     'Schools and teachers who were misinformed and burdened with COPPA compliance responsibilities without adequate disclosure',
     'Consumers relying on accurate image categorization',
     'members of racial and ethnic minorities who risk being stereotyped or misrepresented', 'Chris Cowell',
     'Porcha Woodruff', 'Rona Wang', 'Racial minorities who may have experienced the same result',
     'Potential users of the Savey Meal-bot', 'pedestrians', 'General public', 'Unnamed female students',
     'Francesca Mani', 'Unnamed employee of South Gyeongsang province produce distribution center',
     'Minors Exploited in the Images', 'General public', 'Wolf Blitzer', 'Tom Hanks', 'Sanjay Gupta', 'Sally Bundock',
     'Robin Williams', 'public figures', 'MrBeast', 'Matthew Amroliwala', 'Jesse Waters', 'Ian Hanomansing',
     'General public', 'Gayle King', 'celebrities', 'Keir Starmer', 'General public', 'British Labour Party',
     'Medicare Advantage Plan Patients', 'Healthcare Providers (Doctors and Therapists)', 'elderly patients',
     'Romanians in the United Kingdom', 'Greeks in the United Kingdom', 'Bulgarians in the United Kingdom',
     'British public', 'Albanians in the United Kingdom', 'Anonymous female high school students',
     'Federal Navy Credit Union Customers', 'Rite Aid customers who were women',
     'Rite Aid customers who were minorities', 'Rite Aid customers', 'Sikh people', 'President Joe Biden',
     'Pope Francis', 'Navajo people', 'Minorities', 'Hillary Clinton', 'General public', 'Donald Trump',
     'General Motors', 'Chevrolet of Watsonville', 'Amazon', 'Amazon sellers', 'Amazon Customers',
     "George Carlin's estate", 'Kelly Carlin', 'George Carlin', 'Krista Perry', 'Larissa Martinez', 'Jay Baron',
     'digital artists', 'Taylor Swift', 'General public', 'Georgie Purcell', 'Steve Harvey', 'Sean “Diddy” Combs',
     'General public', 'Denzel Washington', 'Black celebrities', 'Bishop T.D. Jakes', 'General public', 'Chatbot users',
     'Jake Moffatt', 'Unnamed owner of tow truck', 'Bobbi Althoff', 'Julien Fanciulli', 'General public', 'France 24',
     'Bicyclist', 'Unnamed middle school students', 'President Joe Biden', 'transgender people', 'Joe Rogan',
     'Joe Rogan fans', 'TikTok users', 'YouTube users', 'Twitter Users', 'Synthesia', 'Facebook users', 'Voice Actors',
     'Derek Mobley', 'applicants with disabilities', 'applicants over 40', 'African American applicants',
     'Scarlett Johansson', 'female celebrities', 'Emma Watson', 'John Piscitella', 'Jonathan Faridian',
     'DoNotPay customers', 'OpenAI', 'TaskRabbit worker', 'social media users', '2023 Turkey–Syria earthquake victims',
     'Frances Walter', 'elderly patients', 'Marvin von Hagen', 'Seth Lazar', 'Microsoft', 'OpenAI', 'Bing Chat users',
     'Vietnamese Facebook users', 'Lucy Goetz', 'high school students', 'Randal Quran Reid', 'Amazon Fresh',
     'Roomba J7 device owners in project IO', 'iRobot', 'Scale AI', 'Women', 'underage girls', 'female celebrities',
     'transgender travelers', 'gender-nonconforming travelers', 'anonymous Pashto-speaking refugee',
     'Pashto-speaking asylum seekers', 'Dari-speaking asylum seekers', 'COVID-19 patients',
     'COVID-19 healthcare providers', 'New Jersey Transit', 'New Jersey Transit passengers', 'Roberto Mata',
     'Peter LoDuca', 'Steven A. Schwartz', 'People with eating disorders', 'Jordanians in poverty', 'Donald Trump',
     'Anthony Fauci', 'fast food job applicants', 'Amanda Claypool', 'social media users', 'Oriana Albornoz',
     'George Floyd protest participants', 'Derrick Ingram', 'Black Lives Matter activists', 'truck drivers',
     'Tesla drivers', 'David Clough', 'publishing editors', 'publishers', 'San Francisco emergency services',
     'ambulance patient', 'General public', 'Gannett', 'Student athletes', 'Newspapers relying on Gannett',
     'Retool employee who was the victim of the unknown hacker', 'Retool', 'Google', "27 of Retool's clients",
     'Anonymous student', 'Authors', 'Amazon Customers', 'Amazon', 'Potentially exploited groups', 'General public',
     'Consumers', 'Journalistic integrity', 'General public', 'Women', 'Underrepresented genders', 'General public',
     'Advertisers', 'Subaru', 'Major brands whose advertisements were found on these sites', 'GNC', 'General public',
     'Citigroup', 'Nicholas Clayton', 'Misty McGraw', 'Manuel Clayton', 'Illinois residents', 'Amy Newton',
     'Amanda Curry', 'Ukraine', 'News media in Latin America', 'Journalistic integrity', 'General public',
     'people with autism', "lawyers and other experts who were not informed of the tool's limitations",
     'Individuals assessed as high-risk based on the flawed criteria', 'General public', 'General public',
     'Journalists', 'Randal Reid', 'Minorities', 'Black people', 'UK Labour Party', 'Keir Starmer', 'Ukraine',
     'General public', 'European public', 'Democracy', 'American public', 'Disabled people', 'Elderly people',
     'Low-income people', 'Larkin Seiler', 'Tammy Dobbs', 'Children (faces used in deepfakes)',
     'Victims of child sexual abuse (bodies used in videos)', 'General public', 'Unnamed victims in Almendralejo',
     'The Guardian', 'Family of Lilie James', 'General public', 'Journalistic integrity', 'News sources',
     'James Guthrie', "James Guthrie's co-authors", 'Parliament of Australia', 'KPMG', 'Deloitte',
     "Zachariah Crabill's client", 'Zachariah Crabill', 'Legal system', 'General public',
     'Readers of Sports Illustrated', 'Journalistic integrity', 'Tesla workers', 'Tesla engineer', 'Michael Cohen',
     'David M. Schwartz', 'LAION', 'Various people', 'Various organizations', 'General public', 'Children',
     'Trisha Yearwood', 'Taylor Swift', 'Selena Gomez', 'Ree Drummond', 'Oprah', 'Martha Stewart', 'Le Creuset',
     'Lainey Wilson', 'Joanna Gaines', 'Jennifer Lopez', 'General public', 'Fans', 'Blake Shelton',
     'President Joe Biden', 'New Hampshire voters', 'Kathy Sullivan', 'Democracy', 'Harvey Murphy Jr',
     'Ashley Beauchamp', 'DPD', 'Unnamed multinational company', 'Unnamed finance employee', 'General public',
     'Chicago Residents', 'Chicago Minority Communities', 'Hans von Ohain', 'Erik Rossiter',
     'Individual professionals on LinkedIn', 'Global defense companies', 'Cybersecurity firms',
     'Cryptocurrency exchanges', 'Voters in Pakistan', 'PTI (Pakistan Tehreek-e-Insaf)', 'Imran Khan', 'Democracy',
     'General public', 'British voters', 'British Labour Party', 'Keir Starmer', 'Democracy',
     'Public discourse integrity', 'General public', 'Democracy', 'African-American voters', 'Black voters',
     'Classmates of two unnamed middle school boys', 'Investors', 'Journalism', 'Ukraine', 'Oleksiy Danilov',
     'Kyrylo Budanov', 'ChatGPT users', 'Chase Whiteside', 'Palestinians', 'Mosab Abu Toha', 'Gazans', 'celebrities',
     'British public figures', 'Cathy Newman', 'U.S. voters', 'Taiwanese voters', 'General public',
     'Election integrity', 'Democracy', 'Te Ani Solomon', 'Māori Community', 'Maia Sandu', 'Presidency of Moldova',
     'Government of Moldova', 'Democracy', 'General public', 'Indonesian electorate', 'Electoral integrity',
     'Democracy', 'Rana Atif', 'Raja Bashara', 'Naeem Haider Panjutha', 'Imran Khan', 'Palestinians', 'Gazans',
     'Yoon Suk-yeol', 'Korean voters', 'Journalism', 'Electoral integrity', 'Democracy', 'Ferdinand Marcos Jr.',
     'Government of the Philippines', 'Philippines', 'General public', 'General public', 'minors', 'Investors',
     'General public', 'Bill Ackman', 'Cathie Wood', 'Steve Cohen', 'Peter Lynch', 'Ray Dalio', 'Peter Bourget',
     'Kari Lake', 'General public', 'Journalism', 'Democracy', '', 'Public discourse integrity', 'Political integrity',
     'General public', 'Donald Trump', 'Taiwanese voters', 'Lai Ching-te', 'Electoral integrity',
     'Democratic Progressive Party', 'Democracy', 'Political candidates targeted by deepfakes', 'Indian electorate',
     'India', 'Democracy', 'Indian electorate', 'Indian voters', 'Democracy', 'Electoral integrity', 'Media discourse',
     'M. Karunanidhi', 'J. Jayalalithaa', 'Voters', 'Public trust', 'Political figures', 'General public',
     'Electoral integrity', 'Democracy', 'Civic society', 'Eric Eiswert', 'Pikesville High School',
     'Pikesville High School students and staff', 'Baltimore County Public Schools community', 'General public',
     'OpenAI', 'Perplexity AI', 'noyb', 'Max Schrems', 'General public', 'Elizabeth Warren', 'MSNBC', 'Republicans',
     'Democrats', 'Democracy', 'Election integrity', 'General public', 'General public', 'Journalism', 'Democracy',
     'Kim Reynolds', 'Donald Trump', 'General public', 'Democracy', 'Black Americans', 'African-American voters',
     'Olga Loiek', 'Michel Janse', 'Lana Smalls', 'Carrie Williams', 'Shadé Zahrai', 'Google Books',
     'Google Ngram Viewer', 'Researchers', 'General public', 'General public', 'People seeking medical advice',
     'Asian People', 'Interracial couples', 'General public', 'Breeze Liu', 'Scarlett Johansson', 'minors',
     'General public', 'General public', 'People susceptible to radicalism', 'Sara', 'Home Bargains customers',
     'General public', 'Shaun Thompson', 'General public', 'Google users', 'General public', 'Joe Biden',
     'Democratic Party', 'Democracy', 'Election integrity', 'Information integrity', 'Ron DeSantis', 'Elon Musk',
     'George Soros', 'Klaus Schwab', 'Dick Cheney', 'small businesses', 'Advertisers', 'Donald Trump', 'Ron DeSantis',
     "Ron DeSantis's presidential campaign", 'Veterans', 'Survivors of military sexual trauma', 'Female veterans',
     'Facebook users', 'Facebook users in online support communities', 'Journalism', 'Information integrity',
     'General public', 'American citizens', 'Matthew Miller', 'Department of State', 'Biden administration',
     'Joe Biden', 'Texas citizens', 'Texas officials', 'General public', 'Legal professionals', 'Clients of lawyers',
     'Legal system', 'students', 'Turkish YKS exam takers', 'Turkish educational institutions', 'small businesses',
     'Small business customers', 'Small business employees', 'Bee Cups', 'Darn Tough Vermont', 'Jim Carter',
     'Unnamed Fullerton police officer', 'Fullerton Police Department', 'Roberto Spinelli', 'Genoa Prosecutor’s Office',
     'Giovanni Toti', 'Paolo Emilio Signorini', 'Italian general public', 'Unnamed Manchester litigant',
     'Manchester court system', 'General public', 'Auschwitz Memorial Museum', 'Survivors of Holocaust victims',
     'General public', 'Tesla drivers', 'Drivers', 'General public', 'Kristen Gonzalez', 'Clyde Vanel',
     'New York lawmakers', 'Meta', 'Facebook users', 'Ukraine', 'Joe Biden', 'General public', 'Biden administration',
     'New York City small business owners', 'New York City landlords and tenants',
     'New York City employers and employees', 'Eric Adams administration', 'Australian general public', 'Louise Walker',
     'Residents of Brookdale facilities', 'Families of residents of Brookdale facilities',
     'Staff members of Brookdale facilities', 'Website owners', 'Website operators', 'Ernie Smith', 'YouTube creators',
     'General public', 'Content creators', 'X (Twitter) users', 'Israelis', 'Iranians', 'General public', 'Paul Vallas',
     "Paul Vallas's campaign", 'Chicago voters', 'students', 'Professors', 'Community colleges', 'Academic staff',
     'General public', 'Catholics', 'Instagram users', 'Instagram sellers', 'Children', 'University hiring committees',
     'University faculty', 'Scopus', 'Academic journals', 'University job candidates',
     'Individuals coerced into criminal activities', 'Financial fraud victims', 'Human trafficking victims',
     'Unnamed pedestrian', 'Ukrainian general public', 'Joe Biden', 'General public', 'Democratic institutions',
     'Biden presidential campaign', 'American conservatives', 'Paul Skye Lehrman', 'Linnea Sage', 'Voice Actors',
     'Chinese-speaking users of ChatGPT', 'Researchers', 'OpenAI', 'OpenAI users', 'Indian voters',
     'General public misled by deepfake content', 'Political integrity and election fairness', 'Democracy', 'Truth',
     'Developers and businesses incorporating AI-suggested packages', 'Alibaba', 'Individuals with speech impairments',
     'Users whose speech is misinterpreted by Whisper', 'Professionals relying on accurate transcriptions',
     'General public', 'Privacy-conscious individuals', 'People with poor credit scores', 'Lower-income workers',
     'Drivers unaware of data collection', 'Consumers affected by insurance rates', 'Life360 users', 'MyRadar users',
     'Western democracies', 'Volodymyr Zelenskyy', 'Ukraine', 'Secret Service', 'Researchers', 'Media consumers',
     'General public', 'Electoral integrity', 'AI companies facing reputational damage', 'Bank customers',
     'internet users', 'Organizations', 'Individuals targeted by malware', 'Le Pen family', 'French general public',
     'UK general public', 'UK housing benefit claimants', 'Lin (林)', 'Single mothers', 'British single mothers',
     'Zelda Williams', 'Robin Williams', 'Family of Robin Williams', 'Kamala Harris', 'Journalism', 'General public',
     'Donald Trump', 'Kevin Bankston', 'Google users', 'Google Drive users', 'CIOs', 'Enterprise teams',
     'Companies in general', 'Microsoft Copilot users', 'Apple', 'Designers and developers using Figma’s AI tool',
     'Figma users', 'Volkswagen drivers',
     'Potential passengers and road users at risk due to malfunctioning AEB systems', 'Women in Spain',
     'Stefany González Escarraman', 'Spanish general public', 'María', 'Luz', 'Lobna Hemid', 'Eva Jaular',
     '247 women in Spain (unnamed)', 'Kiri Wagstaff', 'PayPal customer service representatives', 'PayPal customers',
     'Hoodline readers', 'Journalism', 'General public', 'Journalism', 'General public', 'Chatbot users',
     'An Appalachian Summer Festival attendees', 'OpenAI', 'Bridget Todd', "Bridget Todd's family", 'Chris Mohney',
     "Chris Mohney's family", 'Bereaved families', 'Dave Fanning', 'BNN Breaking readers', 'Journalism',
     'General public', 'Stella Creasy', 'Priti Patel', 'Penny Mordaunt', 'Gillian Keegan', 'Dehenna Davison',
     'Angela Rayner', 'Olena Zelenska', 'Volodymyr Zelensky', 'Ukrainian government', 'Ukrainian general public',
     'European Union general public', 'Truth', 'Kamala Harris', 'Joe Biden', 'General public', 'American voters',
     'ChatGPT macOS users', 'Instagram users', 'Facebook users', 'Elijah Ott', 'Sabrina Javellana', 'Warehouse Workers',
     'Teachers', 'Researchers', 'Delphi Technologies', 'female applicants', 'Alexa Device Owners',
     'USC Information Sciences Institute', 'Ibrahim Diallo', 'Market Participants', 'Barack Obama', 'Tesla', 'Varied',
     'Video Game Players', 'Delhi Metro Rail Corporation', 'All Life on Earth', 'United States Government',
     'Taylor Swift', 'Nintendo', 'Kamala Harris', 'Joe Biden', 'Donald Trump', 'Disney', 'Alexandria Ocasio-Cortez',
     'Donald Trump', 'Elon Musk', 'X (Twitter) users', 'General public', 'Mark Gordon', 'Wyoming officials',
     'Cody Enterprise', 'Cody Enterprise readers', 'Journalism', 'Stevie Hyder',
     'Richmond-Burton Community High School', 'Kamala Harris', 'Electoral integrity', 'Democracy',
     'American electorate', 'American electorate', 'Electoral integrity', 'Democracy', 'General public']

